meta:
  id: hybrid-orchestration-phase-a-contracts
  version: 1.0.0
  status: approved-for-implementation-planning
  owner: solution-architect
  date: 2026-02-26
  issue: 6

contracts:
  - module: hybrid-orchestrator
    file: .github/framework/hybrid-orchestrator.ts
    interfaces:
      - name: HybridExecutionRequest
        schema:
          task:
            required: [id, title, description, acceptanceCriteria]
          graphNodes: DependencyGraphNodeInput[]
          l2Items: ContextSource[]
          l3Items: ContextSource[]
      - name: HybridExecutionResult
        schema:
          mode: sequential|hybrid
          effectiveFlags: HybridFeatureFlags
          context: ContextHierarchyResult?
          waves: string[][]?
          fallbackReason: string?
    behavior:
      - If hybrid flag is false OR mode is sequential, return sequential fallback.
      - If memoryHierarchyEnabled=true, compose context from L1/L2/L3.
      - If parallelGraphEnabled=true, validate graph; reject invalid graph with cycle path.

  - module: context-hierarchy
    file: .github/framework/context-hierarchy.ts
    interfaces:
      - name: ContextHierarchyInput
        schema:
          task: { id: string, title: string, description: string, acceptanceCriteria: string[] }
          l2Items: ContextSource[]
          l3Items: ContextSource[]
      - name: ContextHierarchyResult
        schema:
          slices:
            item:
              tier: L1|L2|L3
              source: string
              content: string
              estimatedTokens: integer
          totalEstimatedTokens: integer
          truncated: boolean
    guardrails:
      - sanitize_patterns: [api_key, secret, token, password, email]
      - max_l2_comments_respected: true
      - max_context_tokens_respected: true
      - l1_token_budget_cap_applied: true

  - module: dependency-graph
    file: .github/framework/dependency-graph.ts
    interfaces:
      - name: DependencyGraphNodeInput
        schema:
          id: string
          title: string
          agent: AgentId
          dependsOn: string[]?
          priority: P0|P1|P2|P3?
      - name: DependencyGraphPlan
        schema:
          nodes: DependencyGraphNode[]
          waves: string[][]
          validation:
            valid: boolean
            cyclePath: string[]?
    invariants:
      - node ids sorted lexicographically before planning
      - missing dependencies invalidate plan
      - cycles invalidate plan with explicit cycle path
      - wave order deterministic for identical input

errors:
  - code: HYB_GRAPH_VALIDATION_FAILED
    message: Dependency graph validation failed
    details:
      cyclePath: string[]
  - code: HYB_CONTEXT_BUDGET_TRUNCATED
    message: Context slices were truncated to honor budget
    details:
      maxContextTokens: integer
      totalEstimatedTokens: integer

acceptance_criteria_traceability:
  AC-1-build-typecheck:
    proof:
      - npm run typecheck
      - npm run build
    contracts_covered:
      - hybrid-orchestrator
      - context-hierarchy
      - dependency-graph

  AC-2-dag-validation-cycle-path:
    proof:
      - npm test -- dependency-graph.test.ts
    contracts_covered:
      - dependency-graph

  AC-3-context-slices-token-estimates:
    proof:
      - npm test -- context-hierarchy.test.ts
    contracts_covered:
      - context-hierarchy

  AC-4-independent-feature-flags:
    proof:
      - npm test -- hybrid-orchestrator.test.ts
    contracts_covered:
      - hybrid-orchestrator
