meta:
  id: issue31-p0-pricing-integrity-trust-consistency-contracts
  version: 1.0.0
  status: ready-for-tech-lead-planning
  owner: solution-architect
  date: 2026-02-27
  issue: 31
  model_dependency: .github/.system-state/model/issue31_p0_pricing_integrity_trust_consistency_architecture_brief.yaml
  traceability_tags: [PRICING, TRUST, BOOKING, BRAND]

contract_schema_impact_statement:
  no_change:
    - file: src/app/api/booking/availability/route.ts
      reason: Availability contract remains valid for capacity checks and does not own pricing disclosure semantics.
    - file: src/app/api/contact/submissions/route.ts
      reason: Contact submission contract does not influence pricing model correctness.
    - file: src/app/api/reviews/submissions/route.ts
      reason: Review submission contract does not carry booking quote or pricing policy fields.
    - file: src/app/api/reviews/route.ts
      reason: Public review list contract is unaffected by pricing policy normalization.
  change_required:
    - file: src/app/api/bookings/route.ts
      reason: Booking success payload must include deterministic pre-confirmation pricing breakdown semantics.
      required_delta:
        add_response_fields:
          - pricing.subtotal
          - pricing.tax
          - pricing.total
          - pricing.currency
          - pricing.pricingModelLabel
          - pricing.disclosure
    - file: src/app/book/page.tsx
      reason: Booking UX must render canonical pre-confirmation pricing disclosure copy before confirmation.
    - file: src/app/book/components/StepSuites.tsx
      reason: Add-on selection semantics must be policy-aligned and non-contradictory with no-surprise-add-ons claims.
    - file: src/app/pricing/page.tsx
      reason: Remove contradictory upsell/add-on framing and align to canonical transparency policy.
    - file: src/app/pricing/layout.tsx
      reason: Metadata description must avoid contradictory add-on framing.
    - file: src/app/page.tsx
      reason: Home trust claims must remain in sync with route policy matrix.
    - file: src/app/contact/page.tsx
      reason: Contact page pricing/transparency copy must match canonical policy text.
    - file: src/app/reviews/page.tsx
      reason: Reviews page trust/pricing references must match canonical policy text.
    - file: src/app/faq/page.tsx
      reason: FAQ answers must explicitly follow no hidden fees and no surprise add-ons policy.
    - file: src/app/policies/page.tsx
      reason: Policy language must not reintroduce conflicting add-on or hidden-fee behavior.

content_policy_contract:
  name: pricing_trust_policy_contract
  type: content-schema
  routes:
    - /
    - /pricing
    - /book
    - /contact
    - /reviews
    - /faq
    - /policies
  required_claims:
    - clear pricing before confirmation
    - no hidden fees
    - no surprise add-ons
    - premium but fair
  forbidden_claims:
    - add-on upsell framing that implies undisclosed post-quote charges
    - contradictory tax model copy across routes
    - discount or budget positioning language
  conditional_rules:
    - if business_profile.service.boarding.rate.selected_option_id == TBD then numeric_pricing_claims must_be decision_safe

booking_pricing_disclosure_contract:
  endpoint:
    method: POST
    path: /api/bookings
    auth: public
  request_schema_impact: no_change
  response_schema:
    success:
      status: 201
      required_fields:
        - success
        - booking.id
        - booking.bookingNumber
        - booking.checkIn
        - booking.checkOut
        - booking.suite
        - booking.status
        - pricing.subtotal
        - pricing.tax
        - pricing.total
        - pricing.currency
        - pricing.pricingModelLabel
        - pricing.disclosure
    constraints:
      - pricing.total == pricing.subtotal + pricing.tax
      - pricing.disclosure includes "before confirmation"
      - pricing.disclosure includes no hidden fees language

acceptance_traceability:
  AC-I31-001:
    description: Cross-page pricing consistency across required route set.
    contracts:
      - pricing_trust_policy_contract
    tags: [PRICING, TRUST, BOOKING, BRAND]
  AC-I31-002:
    description: No surprise add-ons policy enforcement in pricing and booking experiences.
    contracts:
      - pricing_trust_policy_contract
      - booking_pricing_disclosure_contract
    tags: [PRICING, TRUST]
  AC-I31-003:
    description: Price-before-confirmation clarity including pricing model and taxes language.
    contracts:
      - booking_pricing_disclosure_contract
    tags: [PRICING, BOOKING, TRUST]
  AC-I31-004:
    description: Business-profile copy conformance to premium-fair transparency-first positioning.
    contracts:
      - pricing_trust_policy_contract
    tags: [BRAND, PRICING, TRUST]
  AC-I31-005:
    description: Regression protection with automated tests for copy and booking quote consistency.
    contracts:
      - pricing_trust_policy_contract
      - booking_pricing_disclosure_contract
    tags: [PRICING, TRUST, BOOKING]

required_test_coverage_additions:
  ui_consistency_tests:
    - target: src/app/page.tsx
      assertions:
        - contains_required_pricing_claims
        - contains_no_forbidden_claims
    - target: src/app/pricing/page.tsx
      assertions:
        - contains_required_pricing_claims
        - contains_no_forbidden_claims
    - target: src/app/book/page.tsx
      assertions:
        - contains_pre_confirmation_disclosure
        - contains_tax_model_clarity
    - target: src/app/contact/page.tsx
      assertions:
        - contains_required_pricing_claims
    - target: src/app/reviews/page.tsx
      assertions:
        - contains_required_pricing_claims_if_present
    - target: src/app/faq/page.tsx
      assertions:
        - contains_no_hidden_fees_no_surprise_add_ons_policy
    - target: src/app/policies/page.tsx
      assertions:
        - contains_no_hidden_fees_no_surprise_add_ons_policy
  api_consistency_tests:
    - target: src/app/api/bookings/route.ts
      assertions:
        - response_contains_pricing_breakdown_fields
        - total_math_is_consistent
        - pricing_disclosure_language_present
