meta:
  id: issue29-continuous-improvement-contracts
  version: 1.0.0
  status: proposed-for-implementation-planning
  owner: solution-architect
  date: 2026-02-27
  issue: 29
  model_dependency: .github/.system-state/model/issue29_continuous_improvement_architecture_brief.yaml
  traceability_tags: [BRAND, TRUST, SAFETY, PRICING, BOOKING]

contract_standards:
  public_error_envelope:
    required_fields:
      - errorCode
      - message
      - retryable
      - correlationId
    forbidden_fields:
      - stack
      - raw_email
      - raw_phone
      - raw_message
      - payment_card_data
  redaction_policy_reference: .github/.system-state/security/issue29_continuous_improvement_threat_model.yaml

slice_contract_map:
  I29-S1:
    objective: stabilize trust-critical booking/contact/auth flow reliability baselines
    contracts:
      - name: booking_availability
        method: POST
        path: /api/booking/availability
        request_schema:
          checkIn: string(date)
          checkOut: string(date)
          serviceType: enum[boarding]
          partySize: integer(min=1,max=2)
        response_schema:
          success:
            status: 200
            body:
              isAvailable: boolean
              reasonCode: enum[NONE, NO_CAPACITY, BLACKOUT]
          error:
            status: 400|503
            body:
              errorCode: enum[INVALID_DATE_RANGE, AVAILABILITY_UNAVAILABLE]
              message: string
              retryable: boolean
              correlationId: string
        slos:
          p95_ms: 2000
      - name: contact_submission
        method: POST
        path: /api/contact/submissions
        request_schema:
          fullName: string(min=2,max=120)
          email: string(email)
          phone: string?
          message: string(min=10,max=5000)
          antiAbuseToken: string
          idempotencyKey: string
        response_schema:
          success:
            status: 201
            body:
              submissionId: string
              status: received
          error:
            status: 422|429|503
            body:
              errorCode: enum[CONTACT_VALIDATION_FAILED, CONTACT_RATE_LIMITED, CONTACT_PERSISTENCE_FAILED]
              message: string
              retryable: boolean
              correlationId: string
        slos:
          success_rate_percent_min: 98
      - name: auth_magic_link
        method: POST
        path: /api/auth/magic-link
        request_schema:
          email: string(email)
          intent: enum[sign_in, manage_booking]
        response_schema:
          success:
            status: 202
            body:
              state: sent
              message: string
          error:
            status: 422|500
            body:
              errorCode: enum[INVALID_EMAIL, AUTH_PROVIDER_MISCONFIGURED, AUTH_TRANSIENT_FAILURE]
              message: string
              retryable: boolean
              correlationId: string
    acceptance_mapping:
      - AC-29.1-1
      - AC-29.1-2
      - AC-29.1-3
      - AC-29.1-4
    tags: [TRUST, BOOKING, SAFETY]

  I29-S2:
    objective: clarify booking and pricing content to reinforce trust and conversion
    contracts:
      - name: content_trust_profile_contract
        type: content-schema
        required_claims:
          - only_3_private_suites
          - owner_onsite
          - camera_monitored_safety
          - no_harsh_chemicals
          - no_hidden_fees
        forbidden_claims:
          - fake_scarcity
          - urgency_gimmicks
          - contradictory_pricing_claims
        gating_rule:
          - if business_profile.service.boarding.rate.selected_option_id == TBD then numeric_pricing_claims_for_new_copy must_be_decision_safe
      - name: booking_cta_placement_contract
        type: ux-layout-contract
        required_pages:
          - /
          - /pricing
          - /book
          - /contact
        rule: primary booking cta visible and actionable in first viewport (mobile + desktop)
    acceptance_mapping:
      - AC-29.2-1
      - AC-29.2-2
      - AC-29.2-3
      - AC-29.2-4
    tags: [BRAND, TRUST, PRICING, BOOKING]

  I29-S3:
    objective: achieve WCAG 2.2 AA compliance on core pages
    contracts:
      - name: accessibility_core_pages_contract
        type: compliance-contract
        target_standard: WCAG 2.2 AA
        target_pages:
          - /
          - /pricing
          - /book
          - /contact
        constraints:
          critical_violations: 0
          keyboard_path_success_percent_min: 95
          interactive_contrast_failures: 0
      - name: form_accessibility_contract
        type: semantic-contract
        rules:
          - all form inputs have programmatic labels
          - validation errors are announced to assistive technology
          - heading hierarchy is sequential and meaningful
    acceptance_mapping:
      - AC-29.3-1
      - AC-29.3-2
      - AC-29.3-3
    tags: [TRUST, SAFETY, BOOKING]

  I29-S4:
    objective: harden technical SEO baseline
    contracts:
      - name: robots_asset
        method: GET
        path: /robots.txt
        response_schema:
          success:
            status: 200
            contentType: text/plain
      - name: sitemap_asset
        method: GET
        path: /sitemap.xml
        response_schema:
          success:
            status: 200
            contentType: application/xml
      - name: metadata_uniqueness_contract
        type: seo-metadata-contract
        required_pages:
          - /
          - /about
          - /pricing
          - /book
          - /contact
        rules:
          - unique_title_and_description_per_page
          - keyword_alignment:
              - syracuse dog boarding
              - private dog boarding syracuse
              - small dog boarding syracuse
          - exclude_non_public_routes_from_indexing
    acceptance_mapping:
      - AC-29.4-1
      - AC-29.4-2
      - AC-29.4-3
    tags: [BOOKING, TRUST, BRAND, SAFETY]

  I29-S5:
    objective: enforce privacy-safe logging and redaction on public APIs
    contracts:
      - name: redaction_enforcement_contract
        type: security-contract
        target_endpoints:
          - /api/booking/availability
          - /api/auth/magic-link
          - /api/contact/submissions
          - /api/reviews/submissions
          - /api/reviews
        sensitive_fields:
          - email
          - phone
          - freeText
          - message
          - authorization
          - cookie
        rule: sensitive_fields_are_never_emitted_in_plaintext_logs
        pass_threshold_percent: 100
      - name: pci_boundary_contract
        type: compliance-contract
        rule: card data processing remains delegated to square only
        forbidden_in_app_layers:
          - card_pan
          - cvv
          - expiry
      - name: dependency_security_contract
        type: ci-gate-contract
        rule: high-severity findings block merge unless risk-accepted by security owner
    acceptance_mapping:
      - AC-29.5-1
      - AC-29.5-2
      - AC-29.5-3
    tags: [SAFETY, TRUST, BOOKING]

data_flow_map:
  - slice: I29-S1
    flow: browser -> nextjs api routes -> persistence/provider -> response envelope
    persistence_requirements:
      - idempotency key handling for mutable submissions
      - correlationId generation for all error responses
  - slice: I29-S2
    flow: content model/profile -> page rendering -> user comprehension measurement capture
    persistence_requirements:
      - content assertions stored as QA evidence artifacts
  - slice: I29-S3
    flow: page markup -> accessibility scanners + keyboard scripts -> evidence artifacts
    persistence_requirements:
      - audit outputs versioned under docs/audit_logs
  - slice: I29-S4
    flow: metadata routes -> crawler/search console probes -> indexing baseline evidence
    persistence_requirements:
      - robots/sitemap probe logs retained per release
  - slice: I29-S5
    flow: request payload -> logging middleware -> redaction -> sink
    persistence_requirements:
      - redaction probe fixtures retained as security evidence
