meta:
  id: issue26-p0-trust-booking-brand-contracts
  version: 1.0.0
  status: proposed-for-implementation-planning
  owner: solution-architect
  date: 2026-02-27
  issue: 26
  model_dependency: .github/.system-state/model/issue26_p0_trust_booking_brand_architecture_brief.yaml
  traceability_tags: [BRAND, TRUST, SAFETY, PRICING, BOOKING]

delta_inventory:
  - flow: booking_availability
    current_behavior:
      - availability fetch can fail with technical error and block progression
      - continue action remains disabled without recoverable state
    required_behavior:
      - availability resolution must transition to available or recoverable failure within <=2s p95 target
      - user receives retry affordance and non-technical message on upstream failure
    guards:
      - check_out > check_in
      - required fields present before request dispatch
    failure_semantics:
      recoverable:
        - code: AVAILABILITY_UNAVAILABLE
          http_status: 503
          user_message: "Availability is temporarily unavailable. Please retry."
      validation:
        - code: INVALID_DATE_RANGE
          http_status: 400
          user_message: "Check-out must be after check-in."
    tags: [BOOKING, TRUST, SAFETY]

  - flow: auth_magic_link
    current_behavior:
      - user receives generic configuration error state
    required_behavior:
      - valid email yields confirmation state without exposing provider internals
      - configuration failures surface support-safe UX and actionable server diagnostic code
    guards:
      - email format valid
    failure_semantics:
      config:
        - code: AUTH_PROVIDER_MISCONFIGURED
          http_status: 500
          user_message: "Sign-in is temporarily unavailable. Please contact support."
      validation:
        - code: INVALID_EMAIL
          http_status: 422
          user_message: "Enter a valid email address."
    tags: [TRUST, BOOKING]

  - flow: contact_submit
    current_behavior:
      - submission appears to have no verified backend write and no deterministic success feedback
    required_behavior:
      - successful submit persists and returns a visible confirmation id
      - failed submit preserves user inputs and supports retry
      - anti-abuse threshold returns deterministic throttling response
    guards:
      - schema valid
      - anti_abuse_token present
    failure_semantics:
      throttle:
        - code: CONTACT_RATE_LIMITED
          http_status: 429
          user_message: "Too many attempts. Please wait and try again."
      persistence:
        - code: CONTACT_PERSISTENCE_FAILED
          http_status: 503
          user_message: "We couldn't submit your message right now. Please retry."
    tags: [TRUST, BOOKING]

  - flow: review_submit_moderation
    current_behavior:
      - submit appears non-persistent and moderation lifecycle is not explicit
    required_behavior:
      - valid submit writes pending review record and returns moderation confirmation
      - invalid submit blocks write with field-level validation
      - pending reviews are excluded from public listings
    guards:
      - rating in [1..5]
      - required fields non-empty and length-bounded
    failure_semantics:
      validation:
        - code: REVIEW_VALIDATION_FAILED
          http_status: 422
          user_message: "Please fix highlighted fields before submitting."
      persistence:
        - code: REVIEW_PERSISTENCE_FAILED
          http_status: 503
          user_message: "Review submission failed. Please retry."
    tags: [TRUST, BRAND]

  - flow: seo_baseline
    current_behavior:
      - robots.txt and sitemap.xml return 404
    required_behavior:
      - robots.txt and sitemap.xml exist and return 200 in prod
      - page metadata uses canonical brand naming consistently
    guards:
      - deployment includes metadata routes for robots and sitemap
    failure_semantics:
      routing:
        - code: SEO_ASSET_MISSING
          http_status: 404
          user_message: "Not user-facing; deployment gate fail."
    tags: [BRAND, TRUST, BOOKING]

api_contracts:
  - name: availability_check
    method: POST
    path: /api/booking/availability
    auth: public
    request_schema:
      checkIn: string(date)
      checkOut: string(date)
      serviceType: enum[boarding]
      partySize: integer(min=1,max=2)
    response_schema:
      success:
        status: 200
        body:
          isAvailable: boolean
          reasonCode: enum[NONE, NO_CAPACITY, BLACKOUT]
          nextRetryAfterSeconds: integer?
      error:
        status: 400|503
        body:
          errorCode: enum[INVALID_DATE_RANGE, AVAILABILITY_UNAVAILABLE]
          message: string
          retryable: boolean
          correlationId: string
    slos:
      p95_ms: 2000

  - name: auth_magic_link_send
    method: POST
    path: /api/auth/magic-link
    auth: public
    request_schema:
      email: string(email)
      intent: enum[sign_in, manage_booking]
    response_schema:
      success:
        status: 202
        body:
          state: sent
          message: string
      error:
        status: 422|500
        body:
          errorCode: enum[INVALID_EMAIL, AUTH_PROVIDER_MISCONFIGURED, AUTH_TRANSIENT_FAILURE]
          message: string
          retryable: boolean
          correlationId: string
    slos:
      p95_ms: 2000

  - name: contact_submit
    method: POST
    path: /api/contact/submissions
    auth: public
    request_schema:
      fullName: string(min=2,max=120)
      email: string(email)
      phone: string?
      message: string(min=10,max=5000)
      antiAbuseToken: string
      idempotencyKey: string
    response_schema:
      success:
        status: 201
        body:
          submissionId: string
          status: received
      error:
        status: 422|429|503
        body:
          errorCode: enum[CONTACT_VALIDATION_FAILED, CONTACT_RATE_LIMITED, CONTACT_PERSISTENCE_FAILED]
          message: string
          retryable: boolean
          correlationId: string
    slos:
      p95_ms: 2000

  - name: review_submit
    method: POST
    path: /api/reviews/submissions
    auth: public
    request_schema:
      displayName: string(min=2,max=80)
      rating: integer(min=1,max=5)
      title: string(min=3,max=120)
      body: string(min=20,max=3000)
      stayMonth: string?
      idempotencyKey: string
    response_schema:
      success:
        status: 201
        body:
          reviewId: string
          moderationStatus: pending
          message: string
      error:
        status: 422|503
        body:
          errorCode: enum[REVIEW_VALIDATION_FAILED, REVIEW_PERSISTENCE_FAILED]
          message: string
          retryable: boolean
          correlationId: string
    slos:
      p95_ms: 2000

  - name: public_reviews_list
    method: GET
    path: /api/reviews
    auth: public
    response_schema:
      success:
        status: 200
        body:
          reviews: Review[]
    hard_filter:
      - moderationStatus == approved

  - name: robots_asset
    method: GET
    path: /robots.txt
    auth: public
    response_schema:
      success:
        status: 200
        contentType: text/plain

  - name: sitemap_asset
    method: GET
    path: /sitemap.xml
    auth: public
    response_schema:
      success:
        status: 200
        contentType: application/xml

metadata_consistency_contract:
  canonical_brand_required: "Zaine's Stay & Play"
  disallowed_legacy_brand_strings:
    - Zaines Pet Resort
    - Zaine's Pet Resort & Spa
  required_pages:
    - /
    - /about
    - /pricing
    - /book
    - /contact

acceptance_traceability:
  AC-P0-1-booking-progression:
    contracts: [availability_check]
    tags: [BOOKING, TRUST, SAFETY]
  AC-P0-2-auth-magic-link:
    contracts: [auth_magic_link_send]
    tags: [BOOKING, TRUST]
  AC-P0-3-contact-persistence:
    contracts: [contact_submit]
    tags: [TRUST, BOOKING]
  AC-P0-4-review-moderation:
    contracts: [review_submit, public_reviews_list]
    tags: [TRUST, BRAND]
  AC-P1-3-seo-baseline:
    contracts: [robots_asset, sitemap_asset]
    tags: [BRAND, TRUST, BOOKING]
