# Agent Tier Configuration
# Defines which agents are Core (always loaded) vs Specialist (on-demand)

version: 1.0.0
updated: 2026-02-25

# ============================================================================
# Core Agents (Always Loaded)
# ============================================================================
# These agents are loaded on framework initialization and remain active
# throughout the session. They handle the majority of tasks.

core:
  - id: 00-chief-of-staff
    maxConcurrentTasks: 10
    reason: Entry point for all work

  - id: solution-architect
    maxConcurrentTasks: 3
    reason: High-frequency architecture decisions

  - id: tech-lead
    maxConcurrentTasks: 5
    reason: Implementation planning for most features

  - id: frontend-engineer
    maxConcurrentTasks: 3
    reason: React/Next.js implementation (high volume)

  - id: backend-engineer
    maxConcurrentTasks: 3
    reason: API implementation (high volume)

  - id: qa-test-engineer
    maxConcurrentTasks: 3
    reason: Testing required for all code changes

  - id: quality-director
    maxConcurrentTasks: 3
    reason: Final approval for all PRs

  - id: documentation-engineer
    maxConcurrentTasks: 2
    reason: Frequent docs updates

# ============================================================================
# Specialist Agents (Loaded On-Demand)
# ============================================================================
# These agents are loaded only when needed, reducing framework overhead.
# They handle specialized, less frequent tasks.

specialist:
  - id: product-owner
    maxConcurrentTasks: 1
    loadTriggers:
      - new feature requests
      - requirements clarification
    reason: Needed for new features, not routine implementation

  - id: program-manager
    maxConcurrentTasks: 1
    loadTriggers:
      - multi-sprint planning
      - dependency coordination
    reason: Coordination tasks are periodic, not continuous

  - id: stakeholder-executive
    maxConcurrentTasks: 1
    loadTriggers:
      - budget decisions
      - strategic priorities
    reason: Executive input needed rarely

  - id: platform-engineer
    maxConcurrentTasks: 2
    loadTriggers:
      - infrastructure changes
      - CI/CD updates
      - deployment issues
    reason: Infrastructure changes are less frequent

  - id: data-engineer
    maxConcurrentTasks: 1
    loadTriggers:
      - data pipeline changes
      - migration scripts
    reason: Database work is episodic

  - id: ml-engineer
    maxConcurrentTasks: 1
    loadTriggers:
      - ML model implementation
      - recommendation engine
    reason: No ML features currently active

  - id: ux-designer
    maxConcurrentTasks: 1
    loadTriggers:
      - new user flows
      - design system changes
    reason: Design changes are planned, not ad-hoc

  - id: accessibility-specialist
    maxConcurrentTasks: 1
    loadTriggers:
      - WCAG audits
      - accessibility violations
    reason: Audits are periodic, fixes go to engineers

  - id: performance-engineer
    maxConcurrentTasks: 1
    loadTriggers:
      - performance degradation
      - Core Web Vitals failures
      - bundle size increases
    reason: Performance work is reactive or periodic

  - id: security-engineer
    maxConcurrentTasks: 2
    loadTriggers:
      - security vulnerabilities
      - threat modeling
      - penetration testing
    reason: Security reviews are planned or incident-driven

  - id: privacy-compliance-officer
    maxConcurrentTasks: 1
    loadTriggers:
      - GDPR compliance reviews
      - PII handling changes
    reason: Compliance reviews are periodic

  - id: devops-engineer
    maxConcurrentTasks: 1
    loadTriggers:
      - CI/CD changes
      - deployment automation
    reason: Overlaps with platform-engineer (consolidation candidate)

  - id: sre-engineer
    maxConcurrentTasks: 1
    loadTriggers:
      - SLO violations
      - capacity planning
      - incident postmortems
    reason: SRE work is reactive or periodic

  - id: support-readiness-engineer
    maxConcurrentTasks: 1
    loadTriggers:
      - runbook creation
      - support training
    reason: Support documentation is episodic

  - id: legal-counsel
    maxConcurrentTasks: 1
    loadTriggers:
      - licensing questions
      - terms of service changes
    reason: Legal review is rare

  - id: finance-procurement
    maxConcurrentTasks: 1
    loadTriggers:
      - cost analysis
      - vendor evaluation
    reason: Financial decisions are infrequent

  - id: localization-specialist
    maxConcurrentTasks: 1
    loadTriggers:
      - i18n implementation
      - translation updates
    reason: No i18n currently active

  - id: incident-commander
    maxConcurrentTasks: 1
    loadTriggers:
      - P0 incidents
      - outages
    reason: Incidents are rare (hopefully)

  - id: red-team
    maxConcurrentTasks: 1
    loadTriggers:
      - security audits
      - adversarial testing
    reason: Red team exercises are planned events

# ============================================================================
# Loading Strategy
# ============================================================================

loading:
  # Core agents loaded at startup
  core_load_time_budget: 2000ms

  # Specialist agents lazy-loaded on first use
  specialist_load_time: 500ms

  # Unload specialist agents after inactivity
  specialist_idle_timeout: 30min

  # Maximum number of specialist agents loaded simultaneously
  max_specialist_agents: 5

  # Pre-warm frequently used specialists
  pre_warm:
    - security-engineer
    - platform-engineer
