# Routing Rules Configuration
# Defines smart routing logic for bypassing unnecessary agents

version: 1.0.0
updated: 2026-02-25

# ============================================================================
# Express Lane Rules
# ============================================================================
# Tasks matching these conditions bypass the full workflow entirely

express_lanes:
  - name: Lint Fixes
    condition:
      type: Bug
      scope: Small
      description_matches: '/(lint|eslint|prettier|format)/i'
    route_to: frontend-engineer
    bypass:
      - product-owner
      - solution-architect
      - tech-lead
      - qa-test-engineer
    reason: 'Lint fixes are mechanical - direct to engineer'
    expected_duration: 5min

  - name: Documentation Updates
    condition:
      type: Docs
      scope: Small
      description_not_matches: '/(architecture|adr|system-design)/i'
    route_to: documentation-engineer
    bypass:
      - product-owner
      - solution-architect
      - tech-lead
      - qa-test-engineer
    reason: 'Simple docs updates - direct to docs engineer'
    expected_duration: 10min

  - name: Typo Fixes
    condition:
      description_matches: '/(typo|spelling|grammar)/i'
      scope: Small
    route_to: documentation-engineer
    bypass: [all except quality-director]
    reason: 'Typos are trivial - docs engineer only'
    expected_duration: 3min

  - name: Simple Type Fixes
    condition:
      type: Bug
      scope: Small
      description_matches: '/typecheck|typescript|type error/i'
    route_to: frontend-engineer
    bypass:
      - product-owner
      - solution-architect
      - tech-lead
    reason: 'Type errors are scoped - direct to engineer'
    expected_duration: 10min

# ============================================================================
# Bypass Rules (Partial Routing)
# ============================================================================
# Tasks that skip some agents but not all

bypass_rules:
  - name: Small Bug Fixes
    condition:
      type: Bug
      scope: Small
      priority: [P2, P3]
    skip_agents:
      - product-owner
      - solution-architect
    start_at: tech-lead
    reason: "Small bugs don't need architecture review"

  - name: Small Components
    condition:
      type: Feature
      scope: Small
      description_matches: '/component|button|input|card/i'
    skip_agents:
      - solution-architect
    start_at: tech-lead
    reason: 'Small components follow existing patterns'

  - name: Security P0
    condition:
      type: Security
      priority: P0
    skip_agents: [all]
    start_at: security-engineer
    reason: 'Security emergencies bypass planning'

  - name: Incident P0
    condition:
      type: Incident
      priority: P0
    skip_agents: [all]
    start_at: incident-commander
    reason: 'P0 incidents go to incident commander immediately'

  - name: Simple Refactoring
    condition:
      type: Refactor
      scope: Small
    skip_agents:
      - product-owner
      - solution-architect
    start_at: tech-lead
    reason: 'Small refactors are technical, not architectural'

# ============================================================================
# Standard Routing Chains
# ============================================================================
# Default agent sequences for tasks that don't match bypass rules

standard_chains:
  Feature:
    Small:
      - product-owner
      - tech-lead
      - frontend-engineer
      - qa-test-engineer
      - quality-director
    Medium:
      - product-owner
      - solution-architect
      - tech-lead
      - frontend-engineer
      - qa-test-engineer
      - quality-director
    Large:
      - product-owner
      - solution-architect
      - tech-lead
      - frontend-engineer
      - backend-engineer
      - platform-engineer
      - qa-test-engineer
      - security-engineer
      - quality-director
    XL:
      - stakeholder-executive
      - product-owner
      - solution-architect
      - program-manager
      - tech-lead
      - [frontend-engineer, backend-engineer, platform-engineer] # parallel
      - qa-test-engineer
      - security-engineer
      - performance-engineer
      - quality-director

  Bug:
    Small:
      - tech-lead
      - [frontend-engineer or backend-engineer]
      - qa-test-engineer
      - quality-director
    Medium:
      - qa-test-engineer
      - tech-lead
      - [frontend-engineer or backend-engineer]
      - qa-test-engineer
      - quality-director
    Large:
      - qa-test-engineer
      - solution-architect
      - tech-lead
      - [frontend-engineer, backend-engineer]
      - qa-test-engineer
      - quality-director

  Security:
    all:
      - security-engineer
      - solution-architect
      - tech-lead
      - [frontend-engineer or backend-engineer]
      - qa-test-engineer
      - security-engineer # review again
      - quality-director

  Performance:
    all:
      - performance-engineer
      - tech-lead
      - [frontend-engineer or backend-engineer]
      - qa-test-engineer
      - performance-engineer # verify improvement
      - quality-director

  Docs:
    all:
      - documentation-engineer
      - quality-director

  Incident:
    P0:
      - incident-commander
      - sre-engineer
      - [all relevant engineers in parallel]
      - quality-director
    P1-P3:
      - sre-engineer
      - tech-lead
      - [relevant engineers]
      - quality-director

# ============================================================================
# Routing Metrics
# ============================================================================

metrics:
  track:
    - express_lane_usage_rate
    - bypass_usage_rate
    - average_chain_length
    - time_saved_per_task
    - routing_confidence
    - routing_errors

  targets:
    express_lane_usage: 20% # 20% of tasks should use express lanes
    bypass_usage: 40% # 40% should use some bypass
    average_chain_length_reduction: 30% # 30% fewer agents on average
