# SLO Thresholds Configuration
# Defines performance targets for the agentic framework

version: 1.0.0
updated: 2026-02-25

# ============================================================================
# Task Execution SLOs
# ============================================================================

task_execution:
  # Task completion time targets by complexity
  duration:
    simple:
      p50: 5min
      p95: 15min
      p99: 30min
    medium:
      p50: 30min
      p95: 2h
      p99: 4h
    large:
      p50: 4h
      p95: 1d
      p99: 3d
    xl:
      p50: 3d
      p95: 1w
      p99: 2w

  # Success rate targets
  success_rate:
    target: 95%
    critical_tasks: 99%

  # Retry policy
  retries:
    max_attempts: 3
    backoff: exponential
    initial_delay: 1min

# ============================================================================
# Agent Performance SLOs
# ============================================================================

agent_performance:
  # Response time (time to start work after assignment)
  response_time:
    p50: 30s
    p95: 2min
    p99: 5min

  # Task completion rate per agent
  completion_rate:
    core_agents: 95%
    specialist_agents: 90%

  # Error rate threshold
  error_rate:
    warning: 5%
    critical: 10%

  # Maximum concurrent tasks per agent
  max_concurrent:
    default: 3
    chief_of_staff: 10
    quality_director: 3
    engineers: 3
    specialists: 1

# ============================================================================
# Dispatch Chain SLOs
# ============================================================================

dispatch_chain:
  # Average number of handoffs
  average_length:
    baseline: 5.5
    phase1_target: 4.5
    phase2_target: 3.5
    phase3_target: 3.0

  # Maximum dispatch depth before alert
  max_depth:
    warning: 8
    critical: 10

  # Loop detection
  loop_detection:
    same_agent_threshold: 3
    same_agent_window: 1h

# ============================================================================
# Quality Gate SLOs
# ============================================================================

quality_gates:
  # Gate execution time
  duration:
    G1_lint:
      p50: 10s
      p95: 30s
    G2_format:
      p50: 5s
      p95: 15s
    G3_typecheck:
      p50: 15s
      p95: 45s
    G4_test:
      p50: 30s
      p95: 2min
    G5_build:
      p50: 45s
      p95: 2min
    G6_security:
      p50: 20s
      p95: 1min
    G7_docs:
      p50: 5s
      p95: 15s
    G8_pr:
      p50: 2s
      p95: 5s
    G9_performance:
      p50: 5min
      p95: 10min
    G10_ship:
      p50: 1s
      p95: 5s

  # Pass rate targets
  pass_rate:
    all_gates: 90%
    blocking_gates: 95%

  # Parallelization gain
  parallelization:
    target_improvement: 50%
    baseline_sequential: 10min
    target_parallel: 5min

# ============================================================================
# Developer Experience SLOs
# ============================================================================

developer_experience:
  # Feedback loop time (from commit to first result)
  feedback_loop:
    phase0_baseline: 5min
    phase1_target: 2min
    phase2_target: 30s
    phase3_target: 10s

  # Monitoring dashboard
  dashboard:
    refresh_rate: 2s
    max_latency: 500ms

  # Streaming logs
  logs:
    max_delay: 1s
    buffer_size: 100

  # Abort capability
  abort:
    max_response_time: 3s
    cleanup_time: 10s

# ============================================================================
# Framework Reliability SLOs
# ============================================================================

reliability:
  # Uptime
  uptime:
    target: 99.9%
    allowable_downtime_per_month: 43min

  # Framework initialization time
  initialization:
    core_agents: 2s
    full_framework: 5s

  # Agent loading time
  agent_loading:
    core_agent: 500ms
    specialist_agent: 500ms

  # Context cache hit rate
  cache:
    hit_rate_target: 80%
    max_cache_size: 100MB
    ttl: 1h

# ============================================================================
# Cost & Resource SLOs
# ============================================================================

cost:
  # Token usage targets (cost efficiency)
  token_usage:
    average_per_simple_task: 10000
    average_per_medium_task: 50000
    average_per_large_task: 200000

  # Model usage distribution
  model_distribution:
    gpt5_mini: 60%
    claude_sonnet45: 40%

  # Cost per task targets
  cost_per_task:
    simple: $0.10
    medium: $0.50
    large: $2.00
    xl: $10.00

# ============================================================================
# Monitoring & Alerting SLOs
# ============================================================================

monitoring:
  # Telemetry collection
  telemetry:
    event_loss_rate: <1%
    max_latency: 100ms
    buffer_size: 1000

  # Alert response time
  alerts:
    critical: 1min
    warning: 5min

  # Metrics retention
  retention:
    raw_events: 7d
    aggregated_metrics: 90d
    summary_reports: 1y

# ============================================================================
# Test Coverage SLOs
# ============================================================================

test_coverage:
  # Synthetic task library
  library_size:
    phase0_baseline: 4
    phase1_target: 10
    phase2_target: 30
    phase3_target: 50

  # Test execution time
  execution:
    fast_mode: 5min
    comprehensive_mode: 30min
    chaos_mode: 1h

  # Test success rate
  success_rate:
    happy_path: 100%
    edge_cases: 95%
    failure_modes: 90%

# ============================================================================
# Escalation Thresholds
# ============================================================================

escalation:
  # When to alert Chief of Staff
  chief_of_staff_alert:
    - dispatch_depth >= 8
    - loop_detected
    - agent_error_rate > 10%
    - task_duration > 2x expected

  # When to alert Quality Director
  quality_director_alert:
    - quality_gate_failure_rate > 10%
    - security_gate_failure
    - performance_budget_exceeded

  # When to alert stakeholders
  stakeholder_alert:
    - framework_downtime > 15min
    - cost_overrun > 50%
    - multiple_critical_failures
