name: Bug Report
description: Report a bug or unexpected behavior
title: "bug(<component>): <brief description>"
labels:
  - bug
  - triage
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thank you for reporting a bug. Please fill out the information below to help us diagnose and fix the issue.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System down / Data loss)
        - High (Major feature broken)
        - Medium (Feature partially broken)
        - Low (Minor issue / Cosmetic)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 (Emergency - Fix Now)
        - P1 (Urgent - Fix This Sprint)
        - P2 (Important - Fix Soon)
        - P3 (Nice to Have)
    validations:
      required: true

  - type: input
    id: component
    attributes:
      label: Component
      description: Which component is affected? (e.g., component:checkout, component:api)
      placeholder: component:
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: Brief description of the bug
      placeholder: Clear, one-line description of the issue
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: What is happening right now?
      placeholder: Describe the current (incorrect) behavior
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Describe the expected (correct) behavior
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: Clear, numbered steps to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Where did this occur?
      placeholder: |
        - Browser: [e.g., Chrome 120]
        - OS: [e.g., Windows 11]
        - Device: [e.g., Desktop / iPhone 14]
        - Environment: [e.g., Production / Staging]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Error Messages
      description: Paste any relevant logs, error messages, or stack traces
      placeholder: |
        ```
        Paste error messages or logs here
        ```
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Videos
      description: If applicable, add screenshots or videos to help explain the problem
      placeholder: Drag and drop images or paste image URLs

  - type: textarea
    id: impact
    attributes:
      label: User Impact
      description: Who is affected? How many users? What is the business impact?
      placeholder: |
        - Number of users affected:
        - Business impact:
        - Workaround available:
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria (Fix Validation)
      description: How will we know this bug is fixed?
      placeholder: |
        - [ ] Steps to reproduce no longer produce the error
        - [ ] Existing tests pass
        - [ ] New regression test added
        - [ ] Fix verified in production
    validations:
      required: true

  - type: textarea
    id: risk
    attributes:
      label: Fix Risks & Rollback Plan
      description: What risks are associated with fixing this? How can we rollback if needed?
      placeholder: |
        **Risks:**
        - 

        **Rollback Plan:**
        - 

  - type: textarea
    id: observability
    attributes:
      label: Observability Requirements
      description: How should this be monitored after the fix?
      placeholder: |
        - Metrics to track:
        - Alerts to configure:
        - Validation queries:

  - type: checkboxes
    id: checklist
    attributes:
      label: Bug Report Checklist
      options:
        - label: I have searched for similar issues and this is not a duplicate
          required: true
        - label: I have provided clear steps to reproduce
          required: true
        - label: I have included logs/screenshots where applicable
          required: true
