name: Feature Request
description: Propose a new feature or enhancement
title: "feature(<component>): <brief description>"
labels:
  - feature
  - triage
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Thank you for suggesting a new feature! Please provide detailed information to help us evaluate and prioritize.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 (Critical Business Need)
        - P1 (High Priority)
        - P2 (Medium Priority)
        - P3 (Nice to Have)
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Estimated Scope
      description: How large is this feature?
      options:
        - Small (1-2 days)
        - Medium (3-5 days)
        - Large (1-2 weeks)
        - XL (>2 weeks)
    validations:
      required: true

  - type: input
    id: component
    attributes:
      label: Component
      description: Which component will this affect? (e.g., component:checkout, component:api)
      placeholder: component:
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: One-line description of the feature
      placeholder: Clear, concise description of what this feature does
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Problem Statement
      description: Why is this feature needed? What problem does it solve?
      placeholder: |
        **User Story:**
        As a [type of user],
        I want [some goal],
        So that [some reason].

        **Problem:**
        [Describe the problem this feature solves]
    validations:
      required: true

  - type: textarea
    id: current-workaround
    attributes:
      label: Current Workaround (if any)
      description: How do users currently achieve this (if at all)?
      placeholder: Describe any existing workarounds or manual processes

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: |
        Describe the proposed feature in detail:
        - User workflow
        - UI/UX changes
        - API changes
        - Business logic
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
      placeholder: |
        **Alternative 1:**
        - Description:
        - Pros:
        - Cons:

        **Alternative 2:**
        - Description:
        - Pros:
        - Cons:

  - type: textarea
    id: user-impact
    attributes:
      label: User Impact
      description: Who will benefit? How many users? What is the business value?
      placeholder: |
        - Target users:
        - Number of users impacted:
        - Expected business value:
        - Success metrics:
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete?
      placeholder: |
        - [ ] User can [do something]
        - [ ] System [behaves in some way]
        - [ ] UI displays [something]
        - [ ] Tests cover [scenarios]
    validations:
      required: true

  - type: textarea
    id: design-notes
    attributes:
      label: Design Notes / Technical Approach
      description: Technical implementation details (if known)
      placeholder: |
        **Components to modify:**
        - 

        **New APIs/Endpoints:**
        - 

        **Database changes:**
        - 

        **Dependencies:**
        - 

  - type: textarea
    id: test-plan
    attributes:
      label: Test / Verification Plan
      description: How should this feature be tested?
      placeholder: |
        **Unit Tests:**
        - 

        **Integration Tests:**
        - 

        **E2E Tests:**
        - 

        **Manual Testing:**
        - 

  - type: textarea
    id: risk
    attributes:
      label: Risks & Rollback Considerations
      description: What could go wrong? How can we rollback?
      placeholder: |
        **Risks:**
        - 

        **Backward Compatibility:**
        - 

        **Rollback Plan:**
        - 

        **Feature Flag:**
        - 

  - type: textarea
    id: security
    attributes:
      label: Security Considerations
      description: Are there any security implications?
      placeholder: |
        - Authentication/Authorization changes:
        - PII/sensitive data handling:
        - OWASP concerns:

  - type: textarea
    id: performance
    attributes:
      label: Performance Considerations
      description: Impact on performance, scalability, or load
      placeholder: |
        - Expected load:
        - Performance budget:
        - Caching strategy:

  - type: textarea
    id: observability
    attributes:
      label: Observability Requirements
      description: How should this feature be monitored?
      placeholder: |
        - New metrics:
        - New logs:
        - Alerts:
        - Dashboards:

  - type: textarea
    id: rollout
    attributes:
      label: Rollout Plan
      description: Should this be rolled out gradually?
      placeholder: |
        - [ ] Deploy all at once
        - [ ] Gradual rollout (10% → 25% → 50% → 100%)
        - [ ] Behind feature flag
        - [ ] Beta users first

  - type: checkboxes
    id: checklist
    attributes:
      label: Feature Request Checklist
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: I have provided clear acceptance criteria
          required: true
        - label: I have considered user impact and business value
          required: true
