name: Technical Debt
description: Track technical debt, refactoring, and code quality improvements
title: "tech-debt(<component>): <brief description>"
labels:
  - tech-debt
  - refactor
body:
  - type: markdown
    attributes:
      value: |
        ## Technical Debt
        Document technical debt that should be addressed to improve code quality, maintainability, or developer experience.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 (Blocking Development)
        - P1 (High - Slowing Development)
        - P2 (Medium - Should Address Soon)
        - P3 (Low - Nice to Have)
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Estimated Scope
      description: How much work is required?
      options:
        - Small (1-2 days)
        - Medium (3-5 days)
        - Large (1-2 weeks)
        - XL (>2 weeks)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Debt Category
      description: What type of technical debt is this?
      options:
        - Code Quality (Smells, Duplication)
        - Architecture (Design Patterns, Structure)
        - Performance (Optimization)
        - Testing (Coverage, Test Quality)
        - Documentation (Missing/Outdated Docs)
        - Dependencies (Outdated, Security)
        - Tooling (Build, CI/CD)
        - Configuration (Environment, Settings)
    validations:
      required: true

  - type: input
    id: component
    attributes:
      label: Component
      description: Which component/module is affected?
      placeholder: component:
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Debt Summary
      description: Brief description of the technical debt
      placeholder: One-line summary
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State (What's Wrong)
      description: Describe the current problematic state
      placeholder: |
        What is the current implementation?
        Why is it problematic?
        What issues does it cause?
    validations:
      required: true

  - type: textarea
    id: desired-state
    attributes:
      label: Desired State (What Should Be)
      description: Describe the ideal state after refactoring
      placeholder: |
        What should the implementation look like?
        What problems will this solve?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Why Now
      description: Why should we address this debt now?
      placeholder: |
        **Impact on Development:**
        - 

        **Impact on Maintenance:**
        - 

        **Impact on Performance:**
        - 

        **Risk of NOT Fixing:**
        - 
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: Proposed Refactoring Approach
      description: How should this be refactored?
      placeholder: |
        **Steps:**
        1. 
        2. 
        3. 

        **Files to Change:**
        - 

        **Patterns to Apply:**
        - 
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?
      placeholder: |
        **Alternative 1:**
        - Description:
        - Pros:
        - Cons:

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this refactoring is complete?
      placeholder: |
        - [ ] Code follows [pattern/standard]
        - [ ] Tests pass
        - [ ] Test coverage maintained or improved
        - [ ] No behavior changes (unless intentional)
        - [ ] Documentation updated
    validations:
      required: true

  - type: textarea
    id: test-strategy
    attributes:
      label: Test Strategy
      description: How will we ensure no regressions?
      placeholder: |
        **Before Refactoring:**
        - 

        **During Refactoring:**
        - 

        **After Refactoring:**
        - 
    validations:
      required: true

  - type: textarea
    id: risk
    attributes:
      label: Risk Assessment
      description: What are the risks of this refactoring?
      placeholder: |
        **Risks:**
        - 

        **Mitigation:**
        - 

        **Rollback Plan:**
        - 

        **Backward Compatibility:**
        - 

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies / Blockers
      description: Are there any dependencies or blockers?
      placeholder: |
        **Depends On:**
        - Issue #
        - PR #

        **Blocks:**
        - Issue #

        **External Dependencies:**
        - 

  - type: textarea
    id: metrics
    attributes:
      label: Success Metrics
      description: How will we measure improvement?
      placeholder: |
        **Before:**
        - Metric 1:
        - Metric 2:

        **After (Target):**
        - Metric 1:
        - Metric 2:

  - type: checkboxes
    id: checklist
    attributes:
      label: Technical Debt Checklist
      options:
        - label: I have documented the current problematic state
          required: true
        - label: I have proposed a clear refactoring approach
          required: true
        - label: I have identified risks and mitigation strategies
          required: true
        - label: I have defined acceptance criteria
          required: true
