name: Work Item
description: Structured engineering work item with enterprise traceability requirements
title: "<type>(<scope>): <summary>"
labels:
  - feature
body:
  - type: dropdown
    id: type
    attributes:
      label: Work Type
      description: Select the primary classification for this issue
      options:
        - bug
        - feature
        - chore
        - security
        - performance
        - docs
        - tech-debt
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0
        - P1
        - P2
        - P3
    validations:
      required: true

  - type: input
    id: component
    attributes:
      label: Component label
      description: Use format component:<name> (create if missing)
      placeholder: component:framework
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: Describe the problem and why it matters
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Goals
      description: List clear outcomes this issue must achieve
      placeholder: |
        - Goal 1
        - Goal 2
    validations:
      required: true

  - type: textarea
    id: non-goals
    attributes:
      label: Non-goals
      description: State what this issue intentionally does not include
      placeholder: |
        - Non-goal 1
        - Non-goal 2
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria (testable)
      description: Use checkbox format
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: Implementation notes / approach
      description: Planned technical approach, dependencies, and sequencing
    validations:
      required: true

  - type: textarea
    id: risk
    attributes:
      label: Risk assessment
      description: Security, performance, compatibility, and operational risks
      placeholder: |
        Security:
        Performance:
        Compatibility:
        Operational:
    validations:
      required: true

  - type: textarea
    id: test-plan
    attributes:
      label: Test plan
      description: Tests to add/update and how they will be validated
      placeholder: |
        - Unit:
        - Integration:
        - E2E:
    validations:
      required: true

  - type: textarea
    id: rollback
    attributes:
      label: Rollback plan
      description: Rollback trigger and exact rollback path
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Workflow Requirements
        - Link this issue to a branch named `feature/<issue-id>-slug` or `bugfix/<issue-id>-slug`
        - Use commit format: `<type>(<scope>): <summary> (#<issue>)`
        - PR must include `Closes #<issue>` and complete checklist
