meta:
  id: issue29-continuous-improvement-implementation-plan
  version: 1.0.0
  status: ready-for-engineering-dispatch
  owner: tech-lead
  date: 2026-02-27
  issue: 29
  branch: feature/29-continuous-improvement-tranche1
  upstream_models:
    - .github/.system-state/model/issue29_continuous_improvement_architecture_brief.yaml
    - .github/.system-state/contracts/issue29_continuous_improvement_contracts.yaml
    - .github/.system-state/security/issue29_continuous_improvement_threat_model.yaml
    - .github/.system-state/delivery/issue29_continuous_improvement_execution_plan.yaml
    - .github/.system-state/delivery/issue29_continuous_improvement_qa_trace_matrix.yaml
  traceability_tags: [BRAND, TRUST, SAFETY, PRICING, BOOKING]

execution_policy:
  model_first_order:
    - validate_model_deltas_D29_MODEL_001_to_005
    - implement_contract_envelopes_and_guards
    - implement_backend_persistence_and_redaction_controls
    - wire_frontend_states_and_content_contracts
    - collect_qa_security_and_rollback_evidence
  non_bypass_gates:
    - strict_slice_order_I29_S1_to_I29_S5
    - checkpoint_pass_required_before_next_slice
    - security_signoff_required_for_I29_S1_and_I29_S5
    - qa_trace_evidence_required_for_all_slices
    - rollback_evidence_required_before_any_merge

slice_tickets:
  - ticket_id: I29-S1
    title: Trust-critical funnel reliability baseline
    priority: P0
    owner_pair: [backend-engineer, frontend-engineer]
    objective: Stabilize booking/contact/auth reliability with deterministic contract-valid success and error responses.
    dependencies: []
    contracts:
      - POST /api/booking/availability
      - POST /api/contact/submissions
      - POST /api/auth/magic-link
    implementation_focus:
      backend:
        - enforce request schemas and deterministic status mapping
        - enforce public error envelope fields (errorCode, message, retryable, correlationId)
        - ensure forbidden fields (stack/raw_email/raw_phone/raw_message/payment_card_data) never appear
      frontend:
        - enforce pre-dispatch validation guards on forms and booking date logic
        - render deterministic recoverable failure and retry-safe user states
    checkpoint:
      id: CP1-reliability-baseline
      pass_conditions:
        - booking_availability_probe_p95_ms_lte_2000
        - contact_submission_success_percent_gte_98
        - auth_invalid_email_returns_deterministic_validation_error
    acceptance_ids: [AC-29.1-1, AC-29.1-2, AC-29.1-3, AC-29.1-4]
    tags: [TRUST, BOOKING, SAFETY]
    complexity_points: 10

  - ticket_id: I29-S2
    title: Booking and pricing clarity content-first
    priority: P0
    owner_pair: [frontend-engineer, ux-designer]
    objective: Enforce trust-profile content and CTA placement while pricing option is still decision-safe.
    dependencies: [I29-S1]
    contracts:
      - content_trust_profile_contract
      - booking_cta_placement_contract
    implementation_focus:
      frontend:
        - enforce required trust claims and forbid prohibited claims
        - ensure booking CTA remains visible/actionable on required routes in first viewport
      ux:
        - produce and validate trust-oriented copy and pricing-safe language
        - provide CTA placement evidence for mobile and desktop
    checkpoint:
      id: CP2-content-trust-pricing
      pass_conditions:
        - hero_comprehension_score_percent_gte_85
        - booking_cta_visibility_percent_equals_100_on_required_pages
        - pricing_copy_decision_safe_when_selected_option_is_TBD
    acceptance_ids: [AC-29.2-1, AC-29.2-2, AC-29.2-3, AC-29.2-4]
    tags: [BRAND, TRUST, PRICING, BOOKING]
    complexity_points: 8

  - ticket_id: I29-S3
    title: Accessibility AA remediation for core pages
    priority: P1
    owner_pair: [frontend-engineer, qa-test-engineer]
    objective: Achieve WCAG 2.2 AA compliance contracts for Home/Pricing/Book/Contact.
    dependencies: [I29-S2]
    contracts:
      - accessibility_core_pages_contract
      - form_accessibility_contract
    implementation_focus:
      frontend:
        - remediate semantic, contrast, labeling, and focus-order issues
        - implement assistive-technology-friendly validation messaging
      qa:
        - execute automated and manual accessibility validation scripts
        - attach axe, keyboard, and assistive-tech evidence artifacts
    checkpoint:
      id: CP3-accessibility-aa
      pass_conditions:
        - wcag22aa_critical_violations_core_pages_equals_0
        - keyboard_only_booking_path_success_percent_gte_95
    acceptance_ids: [AC-29.3-1, AC-29.3-2, AC-29.3-3]
    tags: [TRUST, SAFETY, BOOKING]
    complexity_points: 6

  - ticket_id: I29-S4
    title: SEO technical baseline hardening
    priority: P1
    owner_pair: [backend-engineer, frontend-engineer]
    objective: Preserve crawlability assets and metadata/index policy correctness.
    dependencies: [I29-S2]
    contracts:
      - GET /robots.txt
      - GET /sitemap.xml
      - metadata_uniqueness_contract
    implementation_focus:
      backend:
        - ensure robots and sitemap routes are valid and stable
      frontend:
        - ensure required pages have unique metadata aligned to local-intent keywords
        - exclude non-public routes from indexing policy
    checkpoint:
      id: CP4-seo-baseline
      pass_conditions:
        - robots_and_sitemap_status_200
        - unique_metadata_coverage_required_pages_percent_equals_100
        - non_public_routes_excluded_from_indexing
    acceptance_ids: [AC-29.4-1, AC-29.4-2, AC-29.4-3]
    tags: [BOOKING, TRUST, BRAND, SAFETY]
    complexity_points: 5

  - ticket_id: I29-S5
    title: Security and privacy log redaction enforcement
    priority: P1
    owner_pair: [backend-engineer, security-engineer]
    objective: Enforce 100% sensitive-field redaction and preserve PCI delegation boundaries.
    dependencies: [I29-S1, I29-S4]
    contracts:
      - redaction_enforcement_contract
      - dependency_security_contract
      - pci_boundary_contract
    implementation_focus:
      backend:
        - enforce centralized redaction for auth/contact/review/booking logs
        - ensure dependency-security gate blocks high severity findings without acceptance
      security:
        - execute redaction probes and PCI boundary review
        - produce formal PASS/FAIL sign-off before merge progression
    checkpoint:
      id: CP5-security-redaction-compliance
      pass_conditions:
        - redaction_pass_rate_percent_equals_100
        - high_severity_dependency_findings_open_equals_0
        - card_data_touchpoints_in_app_equals_0
    acceptance_ids: [AC-29.5-1, AC-29.5-2, AC-29.5-3]
    tags: [SAFETY, TRUST, BOOKING]
    complexity_points: 7

release_sequence:
  - I29-S1
  - I29-S2
  - I29-S3
  - I29-S4
  - I29-S5

checkpoint_merge_policy:
  before_p0_merge:
    required:
      - CP1-reliability-baseline
      - CP2-content-trust-pricing
      - rollback_drill_minutes_lte_5
      - fallback_runbook_unchanged
  before_p1_merge:
    required:
      - CP3-accessibility-aa
      - CP4-seo-baseline
      - CP5-security-redaction-compliance
      - security_engineer_signoff_approved
      - rollback_drill_minutes_lte_5
      - fallback_runbook_unchanged

quality_gates:
  required_checks:
    - pnpm run lint
    - pnpm run typecheck
    - pnpm run build
    - targeted_tests_per_slice
  evidence_requirements:
    - api_contract_tests_and_probe_logs
    - qa_trace_matrix_evidence_for_all_acceptance_ids
    - security_redaction_probe_and_pci_checklist
    - rollback_readiness_evidence_proving_dns_fallback_lte_5_min