meta:
  id: issue29-continuous-improvement-execution-plan
  version: 1.0.0
  status: ready-for-tech-lead-planning
  owner: solution-architect
  date: 2026-02-27
  issue: 29
  upstream_models:
    - .github/.system-state/model/issue29_continuous_improvement_architecture_brief.yaml
    - .github/.system-state/contracts/issue29_continuous_improvement_contracts.yaml
    - .github/.system-state/security/issue29_continuous_improvement_threat_model.yaml
  traceability_tags: [BRAND, TRUST, SAFETY, PRICING, BOOKING]

sequence_strategy:
  rationale: P0 trust/conversion critical slices first; P1 growth and hardening slices second.
  no_bypass_gates:
    - model_deltas_present_before_code
    - contracts_security_delivery_alignment_required
    - evidence_required_before_gate_pass

slice_sequence:
  - slice_id: I29-S1
    title: trust-critical funnel reliability baseline
    priority: P0
    owners: [tech-lead, backend-engineer, frontend-engineer]
    dependencies: []
    contracts:
      - POST /api/booking/availability
      - POST /api/contact/submissions
      - POST /api/auth/magic-link
    required_invariants:
      - INV-I29-001
      - INV-I29-006
    release_checkpoint:
      name: CP1-reliability-baseline
      pass_conditions:
        - p95_latency_ms_max_2000 for booking availability probe
        - contact_submission_success_percent_min_98
        - auth_invalid_email_returns_deterministic_validation_error
      rollback_triggers:
        - critical_flow_success_percent_below_99
        - error_rate_percent_above_1
        - p95_page_or_api_latency_ms_above_3000

  - slice_id: I29-S2
    title: booking and pricing clarity content-first
    priority: P0
    owners: [tech-lead, frontend-engineer, ux-designer]
    dependencies:
      - I29-S1
    contracts:
      - content_trust_profile_contract
      - booking_cta_placement_contract
    required_invariants:
      - INV-I29-002
      - INV-I29-003
    release_checkpoint:
      name: CP2-content-trust-pricing
      pass_conditions:
        - hero_comprehension_score_percent_min_85
        - booking_cta_visibility_percent_100_on_required_pages
        - pricing_copy_decision_safe_when_selected_option_id_TBD
      rollback_triggers:
        - contradictory_pricing_claim_detected
        - booking_cta_missing_on_any_required_page

  - slice_id: I29-S3
    title: accessibility aa remediation core pages
    priority: P1
    owners: [tech-lead, frontend-engineer, qa-test-engineer]
    dependencies:
      - I29-S2
    contracts:
      - accessibility_core_pages_contract
      - form_accessibility_contract
    required_invariants:
      - INV-I29-004
    release_checkpoint:
      name: CP3-accessibility-aa
      pass_conditions:
        - wcag22aa_critical_violations_core_pages_equals_0
        - keyboard_only_booking_path_success_percent_min_95
      rollback_triggers:
        - any_critical_accessibility_regression_on_core_pages

  - slice_id: I29-S4
    title: seo technical baseline hardening
    priority: P1
    owners: [tech-lead, backend-engineer, frontend-engineer]
    dependencies:
      - I29-S2
    contracts:
      - GET /robots.txt
      - GET /sitemap.xml
      - metadata_uniqueness_contract
    required_invariants:
      - INV-I29-005
    release_checkpoint:
      name: CP4-seo-baseline
      pass_conditions:
        - robots_and_sitemap_status_200
        - unique_metadata_coverage_required_pages_percent_100
        - non_public_routes_excluded_from_indexing
      rollback_triggers:
        - robots_or_sitemap_non_200
        - non_public_routes_indexable

  - slice_id: I29-S5
    title: security and privacy log redaction enforcement
    priority: P1
    owners: [tech-lead, security-engineer, backend-engineer]
    dependencies:
      - I29-S1
      - I29-S4
    contracts:
      - redaction_enforcement_contract
      - pci_boundary_contract
      - dependency_security_contract
    required_invariants:
      - INV-I29-001
      - INV-I29-006
      - SEC-I29-002
      - SEC-I29-005
    release_checkpoint:
      name: CP5-security-redaction-compliance
      pass_conditions:
        - redaction_pass_rate_percent_100
        - high_severity_dependency_findings_open_equals_0
        - card_data_touchpoints_in_app_equals_0
      rollback_triggers:
        - redaction_failure_detected
        - high_severity_vulnerability_without_risk_acceptance

rollback_strategy:
  posture: maintain DNS fallback to Square with <=5 minute rollback window
  pre_release_requirements:
    - rollback drill evidence attached
    - rollback triggers configured and documented
    - no slice introduces state/data coupling that blocks immediate fallback
  rollback_checkpoints:
    - before_P0_merge: verify CP1 and CP2 pass and fallback runbook unchanged
    - before_P1_merge: verify CP3, CP4, CP5 pass and fallback drill remains <=5 minutes

quality_gate_requirements:
  baseline_checks:
    - pnpm run lint
    - pnpm run typecheck
    - pnpm run build
    - targeted tests per slice
  evidence_mandatory:
    - api_contract_tests_and_probe_logs
    - accessibility_reports_and_keyboard_walkthrough
    - metadata_and_route_probe_logs
    - security_redaction_probe_results
    - rollback_readiness_evidence
