meta:
  id: issue31-p0-pricing-integrity-trust-consistency-execution-plan
  version: 1.0.0
  status: ready-for-tech-lead-planning
  owner: solution-architect
  date: 2026-02-27
  issue: 31
  upstream_models:
    - .github/.system-state/model/issue31_p0_pricing_integrity_trust_consistency_architecture_brief.yaml
    - .github/.system-state/contracts/issue31_p0_pricing_integrity_trust_consistency_contracts.yaml
  traceability_tags: [PRICING, TRUST, BOOKING, BRAND]

execution_policy:
  model_first_order:
    - route_copy_policy_contract_enforcement
    - booking_api_pricing_disclosure_contract
    - booking_ui_pre_confirmation_disclosure_rendering
    - automated_regression_and_audit_evidence
  non_bypass_gates:
    - all_issue31_acceptance_criteria_pass
    - route_policy_matrix_coverage_100_percent
    - booking_pricing_disclosure_schema_verified
    - audit_logs_published_under_docs_audit_logs

slice_sequence:
  - slice_id: I31-S1
    title: route pricing policy normalization
    priority: P0
    owners: [tech-lead, frontend-engineer]
    dependencies: []
    routes:
      - /
      - /pricing
      - /book
      - /contact
      - /reviews
      - /faq
      - /policies
    required_invariants:
      - INV-I31-001
      - INV-I31-002
      - INV-I31-004
      - INV-I31-005
    acceptance_mapping:
      - AC-I31-001
      - AC-I31-002
      - AC-I31-004
    release_checkpoint:
      name: CP1-route-policy-consistency
      pass_conditions:
        - required_claims_present_on_all_in_scope_routes
        - forbidden_claims_absent_on_all_in_scope_routes
      rollback_triggers:
        - contradictory_pricing_claim_detected_on_any_in_scope_route

  - slice_id: I31-S2
    title: booking pre-confirmation price disclosure contract
    priority: P0
    owners: [tech-lead, backend-engineer, frontend-engineer]
    dependencies:
      - I31-S1
    contracts:
      - POST /api/bookings
      - booking_pricing_disclosure_contract
    required_invariants:
      - INV-I31-003
    acceptance_mapping:
      - AC-I31-002
      - AC-I31-003
    release_checkpoint:
      name: CP2-booking-price-disclosure
      pass_conditions:
        - api_response_includes_subtotal_tax_total_currency_pricing_model_label
        - pre_confirmation_ui_shows_pricing_disclosure_before_confirm_action
      rollback_triggers:
        - confirmation_path_without_full_pricing_disclosure
        - booking_response_missing_required_pricing_fields

  - slice_id: I31-S3
    title: regression protection and trust audit evidence
    priority: P0
    owners: [tech-lead, qa-test-engineer]
    dependencies:
      - I31-S1
      - I31-S2
    required_invariants:
      - INV-I31-001
      - INV-I31-002
      - INV-I31-003
      - INV-I31-004
      - INV-I31-005
    acceptance_mapping:
      - AC-I31-005
    release_checkpoint:
      name: CP3-regression-and-evidence
      pass_conditions:
        - ui_copy_consistency_tests_green_for_required_routes
        - api_booking_pricing_breakdown_contract_tests_green
        - route_by_route_pricing_consistency_audit_log_published
      rollback_triggers:
        - any_pricing_consistency_regression_in_ci
        - missing_evidence_artifacts_for_issue31

quality_evidence_requirements:
  mandatory_artifacts:
    - docs/audit_logs/ISSUE31_PRICING_CONSISTENCY_ROUTE_AUDIT_2026-02-27.md
    - docs/audit_logs/ISSUE31_BOOKING_PRICE_DISCLOSURE_API_EVIDENCE_2026-02-27.md
    - docs/audit_logs/ISSUE31_TEST_EXECUTION_SUMMARY_2026-02-27.md
  required_test_commands:
    - pnpm run test:app -- src/__tests__/issue31-pricing-consistency.test.ts
    - pnpm run test:app -- src/__tests__/issue31-booking-pricing-contract.test.ts
  ci_gates:
    - pnpm run lint
    - pnpm run typecheck
    - pnpm run test:app
    - pnpm run build

approval_packet_requirements:
  quality_director_packet_must_include:
    - explicit_issue31_ac_pass_fail_table
    - objective_evidence_links_under_docs_audit_logs
    - formal_approval_request_statement
    - next_biggest_thing_proposal
  next_biggest_thing_proposal:
    id: I31-NBT-P1
    title: Brand authenticity and trust narrative alignment
    effort: M
    acceptance_criteria:
      - remove_generic_or_fabricated_team_personas_from_about
      - align_about_story_to_owner_led_syracuse_local_profile
      - remove_or_rewrite_unverifiable_trust_claims_to_evidence_backed_copy
    traceability_tags: [BRAND, TRUST, SAFETY]
