meta:
  id: issue26-p0-trust-booking-brand-qa-trace-matrix
  version: 1.0.0
  status: ready-for-qa-execution
  owner: tech-lead
  date: 2026-02-27
  issue: 26
  branch: feature/26-p0-trust-booking-brand
  source_contracts: .github/.system-state/contracts/issue26_p0_trust_booking_brand_contracts.yaml
  traceability_tags: [BRAND, TRUST, SAFETY, PRICING, BOOKING]

matrix:
  - slice: I26-S1
    acceptance_id: AC-P0-1-booking-progression
    user_story: P0-1 Booking Funnel Must Complete
    required_tags: [BOOKING, TRUST, SAFETY]
    contract_endpoints:
      - POST /api/booking/availability
    invariants:
      - INV-I26-001
      - INV-I26-002
    test_cases:
      - case_id: TC-I26-S1-HP
        scenario: valid dates and service allow progression to suite selection
        expected:
          - continue enabled only after available state
          - response/failure state shown <=2s p95 target
      - case_id: TC-I26-S1-FAIL
        scenario: availability upstream unavailable
        expected:
          - user receives non-technical retry-safe message
          - error response includes AVAILABILITY_UNAVAILABLE with correlationId
      - case_id: TC-I26-S1-GUARD
        scenario: check-out <= check-in
        expected:
          - inline validation blocks request dispatch
          - INVALID_DATE_RANGE path represented without network call
    evidence_required:
      - network_capture_with_status_and_error_code
      - ui_state_transition_screenshots_or_video
      - latency_sample_summary

  - slice: I26-S2
    acceptance_id: AC-P0-2-auth-magic-link
    user_story: P0-2 Auth Sign-In Must Be Configured and Usable
    required_tags: [BOOKING, TRUST]
    contract_endpoints:
      - POST /api/auth/magic-link
    invariants:
      - INV-I26-003
    test_cases:
      - case_id: TC-I26-S2-HP
        scenario: valid email submission
        expected:
          - deterministic non-error confirmation state
          - state transitions to sent
      - case_id: TC-I26-S2-GUARD
        scenario: invalid email format
        expected:
          - inline validation blocks dispatch
          - INVALID_EMAIL path shown
      - case_id: TC-I26-S2-CONFIG
        scenario: auth provider misconfigured
        expected:
          - support-safe message shown without provider internals
          - AUTH_PROVIDER_MISCONFIGURED logged server-side with correlationId
    evidence_required:
      - ui_capture_for_sent_invalid_misconfigured_states
      - server_log_excerpt_redacted_with_error_code_and_correlation_id
      - latency_sample_summary

  - slice: I26-S3
    acceptance_id:
      - AC-P0-3-contact-persistence
      - AC-P0-4-review-moderation
    user_story:
      - P0-3 Contact Form Must Persist and Confirm
      - P0-4 Reviews Submission Must Reflect True Moderation Workflow
    required_tags: [TRUST, BOOKING, BRAND]
    contract_endpoints:
      - POST /api/contact/submissions
      - POST /api/reviews/submissions
      - GET /api/reviews
    invariants:
      - INV-I26-004
      - INV-I26-005
    test_cases:
      - case_id: TC-I26-S3-CONTACT-HP
        scenario: valid contact submission
        expected:
          - backend write acknowledged with submissionId
          - visible confirmation rendered
      - case_id: TC-I26-S3-CONTACT-RETRY
        scenario: contact persistence failure
        expected:
          - CONTACT_PERSISTENCE_FAILED and correlationId returned
          - form values preserved for retry
      - case_id: TC-I26-S3-CONTACT-THROTTLE
        scenario: repeated submit attempts exceed threshold
        expected:
          - CONTACT_RATE_LIMITED returned
          - no destructive loss of entered values
      - case_id: TC-I26-S3-REVIEW-HP
        scenario: valid review submission
        expected:
          - review persisted with moderationStatus pending
          - user sees moderation confirmation
      - case_id: TC-I26-S3-REVIEW-VLD
        scenario: invalid review payload
        expected:
          - REVIEW_VALIDATION_FAILED with field-level errors
          - no write operation observed
      - case_id: TC-I26-S3-REVIEW-FILTER
        scenario: list public reviews
        expected:
          - only approved moderation records are returned
    evidence_required:
      - persistence_acknowledgment_payloads
      - retry_behavior_capture
      - approved_only_listing_assertion

  - slice: I26-S4
    acceptance_id: AC-P1-3-seo-baseline
    user_story: P1-3 Legal/Metadata Consistency and SEO Baseline
    required_tags: [BRAND, TRUST, BOOKING]
    contract_endpoints:
      - GET /robots.txt
      - GET /sitemap.xml
    invariants:
      - INV-I26-006
      - INV-I26-007
    test_cases:
      - case_id: TC-I26-S4-ROUTES
        scenario: crawlability assets
        expected:
          - /robots.txt status 200
          - /sitemap.xml status 200
      - case_id: TC-I26-S4-BRAND
        scenario: metadata/title consistency on required pages
        expected:
          - canonical brand string appears as Zaine's Stay & Play
          - no disallowed legacy brand strings
    evidence_required:
      - route_status_capture
      - metadata_audit_output

gating:
  p0_release_blockers:
    - I26-S1 evidence complete and passing
    - I26-S2 evidence complete and passing
    - I26-S3 evidence complete and passing
    - security_redaction_review == approved
  p1_merge_blockers:
    - I26-S4 evidence complete and passing
    - risk_R-26-001 decision recorded
    - risk_R-26-002 approval recorded
