meta:
  id: issue26-p0-trust-booking-brand-implementation-plan
  version: 1.0.0
  status: ready-for-engineering-dispatch
  owner: tech-lead
  date: 2026-02-27
  issue: 26
  branch: feature/26-p0-trust-booking-brand
  upstream_models:
    - .github/.system-state/model/issue26_p0_trust_booking_brand_architecture_brief.yaml
    - .github/.system-state/contracts/issue26_p0_trust_booking_brand_contracts.yaml
    - .github/.system-state/model/issue26_p0_trust_booking_brand_risk_register.yaml
  traceability_tags: [BRAND, TRUST, SAFETY, PRICING, BOOKING]

execution_policy:
  model_first_order:
    - contracts_and_state_transitions
    - server_validation_and_error_code_mapping
    - persistence_and_idempotency
    - ui_state_wiring
    - copy_and_metadata_polish
  non_bypass_gates:
    - all_p0_acceptance_criteria_pass
    - log_redaction_verified_by_security_engineer
    - qa_evidence_published_for_each_slice

slice_tickets:
  - ticket_id: I26-S1
    title: Booking availability reliability
    priority: P0
    owners:
      frontend_engineer: required
      backend_engineer: required
    owner_pair: [frontend-engineer, backend-engineer]
    objective: Enforce booking availability state machine with recoverable degraded UX and pre-dispatch date guard.
    scope:
      contracts:
        - POST /api/booking/availability
      state_machine:
        - BookingAvailabilityFlow idle->validating_input->checking_availability->available|unavailable_recoverable|service_degraded
      invariants:
        - INV-I26-001
        - INV-I26-002
    backend_tasks:
      - implement request schema validation and INVALID_DATE_RANGE response mapping
      - return AVAILABILITY_UNAVAILABLE with retryable=true and correlationId on service failure
      - ensure p95 target <=2000ms under production-like profile for response state
    frontend_tasks:
      - prevent network dispatch for invalid date range and surface inline validation
      - enable progression only when API indicates available state
      - show non-technical retry-safe UX copy for degraded/unavailable states
    acceptance_criteria:
      - AC-P0-1-booking-progression
    tags: [BOOKING, TRUST, SAFETY]
    dependencies: []
    complexity_points: 8

  - ticket_id: I26-S2
    title: Auth magic-link reliability
    priority: P0
    owners:
      frontend_engineer: required
      backend_engineer: required
    owner_pair: [frontend-engineer, backend-engineer]
    objective: Deliver deterministic sign-in state transitions with support-safe misconfiguration handling.
    scope:
      contracts:
        - POST /api/auth/magic-link
      state_machine:
        - MagicLinkFlow idle->validating_email->sending_link->sent|invalid_email|provider_misconfigured|transient_failure
      invariants:
        - INV-I26-003
    backend_tasks:
      - enforce strict email schema and INVALID_EMAIL mapping
      - map provider config faults to AUTH_PROVIDER_MISCONFIGURED and correlationId
      - map transient provider faults to AUTH_TRANSIENT_FAILURE with retryable=true
    frontend_tasks:
      - block submit dispatch for invalid email and show inline validation
      - render deterministic success state for sent responses
      - display support-safe messaging without provider internals for misconfiguration path
    acceptance_criteria:
      - AC-P0-2-auth-magic-link
    tags: [BOOKING, TRUST]
    dependencies:
      - I26-S1
    complexity_points: 5

  - ticket_id: I26-S3
    title: Contact and review persistence reliability
    priority: P0
    owners:
      frontend_engineer: required
      backend_engineer: required
    owner_pair: [frontend-engineer, backend-engineer]
    objective: Ensure contact/review writes persist with idempotency, anti-abuse controls, and moderation-safe listing.
    scope:
      contracts:
        - POST /api/contact/submissions
        - POST /api/reviews/submissions
        - GET /api/reviews
      state_machines:
        - ContactSubmissionFlow
        - ReviewModerationFlow
      invariants:
        - INV-I26-004
        - INV-I26-005
    backend_tasks:
      - persist contact/review payloads and return submission/review ids on success
      - enforce idempotencyKey handling and anti-abuse threshold response codes
      - hard-filter public reviews to approved moderation status only
    frontend_tasks:
      - maintain entered form values on retryable failures
      - display deterministic success confirmations from persistence acknowledgments
      - show field-level validation errors and prevent false-success UX
    acceptance_criteria:
      - AC-P0-3-contact-persistence
      - AC-P0-4-review-moderation
    tags: [TRUST, BOOKING, BRAND]
    dependencies:
      - I26-S1
    complexity_points: 8

  - ticket_id: I26-S4
    title: SEO and metadata baseline
    priority: P1
    owners:
      frontend_engineer: optional
      backend_engineer: required
    owner_pair: [frontend-engineer, backend-engineer]
    objective: Restore crawlability assets and canonical brand naming consistency.
    scope:
      contracts:
        - GET /robots.txt
        - GET /sitemap.xml
      invariants:
        - INV-I26-006
        - INV-I26-007
    acceptance_criteria:
      - AC-P1-3-seo-baseline
    tags: [BRAND, TRUST, BOOKING]
    dependencies:
      - I26-S1
      - I26-S2
      - I26-S3
    complexity_points: 3

  - ticket_id: I26-S5
    title: Brand and pricing copy alignment
    priority: P1
    owners:
      frontend_engineer: required
      backend_engineer: optional
    owner_pair: [frontend-engineer, backend-engineer]
    objective: Align IA/copy to canonical 3-suite profile and keep pricing language within approved business decision.
    constraints:
      - requires pricing_decision from risk R-26-001
      - requires brand_positioning_approval from risk R-26-002
    tags: [BRAND, TRUST, PRICING, BOOKING]
    dependencies:
      - I26-S4
    complexity_points: 4

release_sequence:
  - I26-S1
  - I26-S2
  - I26-S3
  - I26-S4
  - I26-S5

quality_gates:
  required_checks:
    - pnpm lint
    - pnpm typecheck
    - pnpm test -- --runInBand
    - pnpm build
  additional_evidence:
    - api_contract_assertions_for_P0_endpoints
    - no_raw_pii_in_error_logs
    - p95_response_state_target_at_or_below_2s_for_p0_flows
