meta:
  id: issue29-continuous-improvement-qa-trace-matrix
  version: 1.0.0
  status: ready-for-qa-execution
  owner: solution-architect
  date: 2026-02-27
  issue: 29
  source_contracts: .github/.system-state/contracts/issue29_continuous_improvement_contracts.yaml
  traceability_tags: [BRAND, TRUST, SAFETY, PRICING, BOOKING]

matrix:
  - slice: I29-S1
    story: 29.1 reliability baseline
    acceptance_ids:
      - AC-29.1-1
      - AC-29.1-2
      - AC-29.1-3
      - AC-29.1-4
    required_tags: [TRUST, BOOKING, SAFETY]
    contract_endpoints:
      - POST /api/booking/availability
      - POST /api/contact/submissions
      - POST /api/auth/magic-link
    invariants:
      - INV-I29-001
      - INV-I29-006
    test_cases:
      - case_id: TC-I29-S1-BOOKING-HP
        scenario: booking availability with valid date range
        expected:
          - contract-valid success payload
          - p95 latency <= 2000ms
      - case_id: TC-I29-S1-BOOKING-GUARD
        scenario: booking availability with invalid date range
        expected:
          - deterministic validation error
          - no stack leakage
      - case_id: TC-I29-S1-CONTACT-HP
        scenario: contact submission valid payload
        expected:
          - submission accepted with success >=98%
          - idempotency prevents duplicate side effects
      - case_id: TC-I29-S1-AUTH-VLD
        scenario: malformed email to magic-link endpoint
        expected:
          - deterministic validation error response
          - logs contain no raw sensitive fields
    evidence_required:
      - api_contract_test_results
      - latency_probe_summary
      - redaction_probe_log_excerpt

  - slice: I29-S2
    story: 29.2 booking + pricing clarity
    acceptance_ids:
      - AC-29.2-1
      - AC-29.2-2
      - AC-29.2-3
      - AC-29.2-4
    required_tags: [BRAND, TRUST, PRICING, BOOKING]
    contracts:
      - content_trust_profile_contract
      - booking_cta_placement_contract
    invariants:
      - INV-I29-002
      - INV-I29-003
    test_cases:
      - case_id: TC-I29-S2-CONTENT-5SEC
        scenario: 5-second comprehension test on hero/pricing trust points
        expected:
          - comprehension score >=85%
      - case_id: TC-I29-S2-PRICING-SAFE
        scenario: pricing decision still pending
        expected:
          - copy is decision-safe with no contradictory dollar claims
      - case_id: TC-I29-S2-CTA-VIEWPORT
        scenario: required pages above-the-fold CTA check
        expected:
          - booking CTA visible and actionable on all required pages
      - case_id: TC-I29-S2-PROHIBITED-CLAIMS
        scenario: trust section copy review
        expected:
          - no fake scarcity or urgency gimmick claims
    evidence_required:
      - content_qa_checklist
      - 5_second_test_summary
      - cta_viewport_snapshots

  - slice: I29-S3
    story: 29.3 accessibility aa core pages
    acceptance_ids:
      - AC-29.3-1
      - AC-29.3-2
      - AC-29.3-3
    required_tags: [TRUST, SAFETY, BOOKING]
    contracts:
      - accessibility_core_pages_contract
      - form_accessibility_contract
    invariants:
      - INV-I29-004
    test_cases:
      - case_id: TC-I29-S3-AXE
        scenario: automated accessibility scans on core pages
        expected:
          - critical violations = 0
      - case_id: TC-I29-S3-KEYBOARD
        scenario: keyboard-only traversal through nav, forms, CTAs
        expected:
          - logical focus order and operable controls
      - case_id: TC-I29-S3-SR
        scenario: screen reader semantic parsing
        expected:
          - headings, labels, and errors announced meaningfully
    evidence_required:
      - axe_report_artifacts
      - keyboard_walkthrough_evidence
      - assistive_tech_checklist

  - slice: I29-S4
    story: 29.4 seo baseline hardening
    acceptance_ids:
      - AC-29.4-1
      - AC-29.4-2
      - AC-29.4-3
    required_tags: [BOOKING, TRUST, BRAND, SAFETY]
    contract_endpoints:
      - GET /robots.txt
      - GET /sitemap.xml
    invariants:
      - INV-I29-005
    test_cases:
      - case_id: TC-I29-S4-ENDPOINTS
        scenario: robots/sitemap probes
        expected:
          - both endpoints return 200 with valid content
      - case_id: TC-I29-S4-METADATA
        scenario: required-page metadata validation
        expected:
          - unique title/description aligned to local intent keywords
      - case_id: TC-I29-S4-INDEXING
        scenario: crawl policy review for non-public routes
        expected:
          - system routes excluded from indexing policy
    evidence_required:
      - robots_sitemap_probe_logs
      - metadata_validation_logs
      - crawl_policy_checklist

  - slice: I29-S5
    story: 29.5 security privacy redaction
    acceptance_ids:
      - AC-29.5-1
      - AC-29.5-2
      - AC-29.5-3
    required_tags: [SAFETY, TRUST, BOOKING]
    contracts:
      - redaction_enforcement_contract
      - dependency_security_contract
      - pci_boundary_contract
    invariants:
      - INV-I29-006
      - SEC-I29-002
      - SEC-I29-005
    test_cases:
      - case_id: TC-I29-S5-REDACTION
        scenario: sensitive-field payloads through public APIs
        expected:
          - 100% sensitive-field redaction in logs
      - case_id: TC-I29-S5-DEPENDENCY
        scenario: high severity security scan findings
        expected:
          - merge blocked when high severity > 0 without formal risk acceptance
      - case_id: TC-I29-S5-PCI
        scenario: payment data flow audit
        expected:
          - no card data handled by app-controlled code paths
    evidence_required:
      - redaction_probe_artifacts
      - ci_security_scan_artifact
      - pci_delegation_checklist

gating:
  p0_release_blockers:
    - I29-S1 evidence complete and passing
    - I29-S2 evidence complete and passing
  p1_merge_blockers:
    - I29-S3 evidence complete and passing
    - I29-S4 evidence complete and passing
    - I29-S5 evidence complete and passing
    - security_engineer_signoff == approved
