meta:
  id: issue31-p0-pricing-integrity-trust-consistency-implementation-plan
  version: 1.0.0
  status: ready-for-engineering-dispatch
  owner: tech-lead
  date: 2026-02-27
  issue: 31
  branch: feature/31-pricing-integrity-trust-consistency
  upstream_models:
    - .github/.system-state/model/issue31_p0_pricing_integrity_trust_consistency_architecture_brief.yaml
    - .github/.system-state/contracts/issue31_p0_pricing_integrity_trust_consistency_contracts.yaml
    - .github/.system-state/delivery/issue31_p0_pricing_integrity_trust_consistency_execution_plan.yaml
  traceability_tags: [PRICING, TRUST, BOOKING, BRAND]

execution_policy:
  model_first_order:
    - I31-S1-cross-route-policy-normalization
    - I31-S2-booking-price-disclosure-contract
    - I31-S3-regression-protection-and-audit-evidence
  non_bypass_gates:
    - CP1-route-policy-consistency-pass-required-before-CP2
    - CP2-booking-price-disclosure-pass-required-before-CP3
    - CP3-regression-and-evidence-pass-required-before-quality-director-submission

slice_tickets:
  - ticket_id: I31-S1
    title: Cross-route pricing policy normalization
    priority: P0
    owner_pair: [frontend-engineer, tech-lead]
    dependencies: []
    routes:
      - /
      - /pricing
      - /book
      - /contact
      - /reviews
      - /faq
      - /policies
    files:
      - src/app/page.tsx
      - src/app/pricing/page.tsx
      - src/app/pricing/layout.tsx
      - src/app/book/page.tsx
      - src/app/book/components/StepSuites.tsx
      - src/app/contact/page.tsx
      - src/app/reviews/page.tsx
      - src/app/faq/page.tsx
      - src/app/policies/page.tsx
    acceptance_mapping:
      - AC-I31-001
      - AC-I31-002
      - AC-I31-004
    required_invariants:
      - INV-I31-001
      - INV-I31-002
      - INV-I31-004
      - INV-I31-005
    checkpoint:
      id: CP1-route-policy-consistency
      pass_conditions:
        - required_claims_present_on_all_in_scope_routes
        - forbidden_claims_absent_on_all_in_scope_routes
      no_bypass_rule: true
    complexity_points: 6

  - ticket_id: I31-S2
    title: Booking price-before-confirmation disclosure semantics
    priority: P0
    owner_pair: [backend-engineer, frontend-engineer]
    dependencies:
      - I31-S1
    contracts:
      - POST /api/bookings
      - booking_pricing_disclosure_contract
    files:
      - src/app/api/bookings/route.ts
      - src/app/book/page.tsx
      - src/app/book/components/StepSuites.tsx
    required_response_fields:
      - pricing.subtotal
      - pricing.tax
      - pricing.total
      - pricing.currency
      - pricing.pricingModelLabel
      - pricing.disclosure
    acceptance_mapping:
      - AC-I31-002
      - AC-I31-003
    required_invariants:
      - INV-I31-003
    checkpoint:
      id: CP2-booking-price-disclosure
      pass_conditions:
        - api_response_includes_required_pricing_breakdown_fields
        - pricing_total_math_is_consistent
        - pricing_disclosure_rendered_before_confirmation_action
      no_bypass_rule: true
    complexity_points: 6

  - ticket_id: I31-S3
    title: Regression protection and audit evidence
    priority: P0
    owner_pair: [qa-test-engineer, tech-lead]
    dependencies:
      - I31-S1
      - I31-S2
    tests:
      - src/__tests__/issue31-pricing-consistency.test.ts
      - src/__tests__/issue31-booking-pricing-contract.test.ts
    mandatory_artifacts:
      - docs/audit_logs/ISSUE31_PRICING_CONSISTENCY_ROUTE_AUDIT_2026-02-27.md
      - docs/audit_logs/ISSUE31_BOOKING_PRICE_DISCLOSURE_API_EVIDENCE_2026-02-27.md
      - docs/audit_logs/ISSUE31_TEST_EXECUTION_SUMMARY_2026-02-27.md
    acceptance_mapping:
      - AC-I31-005
    required_invariants:
      - INV-I31-001
      - INV-I31-002
      - INV-I31-003
      - INV-I31-004
      - INV-I31-005
    checkpoint:
      id: CP3-regression-and-evidence
      pass_conditions:
        - pricing_consistency_tests_green_for_all_in_scope_routes
        - bookings_contract_pricing_breakdown_tests_green
        - all_mandatory_issue31_audit_logs_published
      no_bypass_rule: true
    complexity_points: 5

release_sequence:
  - I31-S1
  - I31-S2
  - I31-S3

quality_gates:
  required_checks:
    - pnpm run lint
    - pnpm run typecheck
    - pnpm run test:app
    - pnpm run build
  evidence_requirements:
    - ac_matrix_for_AC-I31-001_through_AC-I31-005
    - objective_links_to_mandatory_docs_audit_logs_artifacts
    - formal_approval_request_to_quality_director

approval_packet_requirements:
  target_agent: quality-director
  include_items:
    - formal_approval_request_for_issue31
    - ac_pass_fail_matrix_with_objective_evidence_links
    - next_biggest_thing_proposal
  next_biggest_thing_proposal:
    id: I31-NBT-P1
    title: Brand authenticity and trust narrative alignment
    effort: M
    acceptance_criteria:
      - Remove generic/fabricated team personas from About page.
      - Align About narrative to owner-led, Syracuse-local, small-capacity profile.
      - Ensure trust claims are evidence-backed and non-generic.
    traceability_tags: [BRAND, TRUST, SAFETY]
