FROM node:20-alpine
WORKDIR /usr/src/app
COPY package.json pnpm-lock.yaml ./
RUN corepack enable && corepack prepare pnpm@latest --activate && pnpm install --frozen-lockfile --prod
COPY . .
ENV NODE_ENV=production
CMD ["node", "scripts/worker.js"]
