version: 1.0.0
updated: YYYY-MM-DD
status: draft
owner: product-owner

business:
  name: ""
  location:
    city: ""
    county: ""
    state: ""
  category: ""

positioning:
  capacity:
    suites_total: 0
    suite_dimensions_ft: ""
    occupancy_per_suite: ""
  market_position: ""
  differentiation: []

brand:
  five_second_impression: []
  personality: []
  emotional_core: []
  summary_statement: ""

audience:
  primary_segments: []

voice:
  style: []
  rules: []

visual:
  palette:
    primary: ""
    accent: ""
    accent_usage: []
    constraints: []
  typography: []
  photography:
    stock_images_allowed: false
    required_subjects: []

service:
  boarding:
    product_name: ""
    rate:
      decision_status: draft
      decision_owner: ""
      decision_due_date: YYYY-MM-DD
      decision_rationale: ""
      decision_approved_by: ""
      decision_approved_at: YYYY-MM-DD
      amount_usd: 0
      unit: night
      tax_included: true
    pricing_message: []
    positioning_rules: []

information_architecture:
  required_pages: []
  components:
    testimonials:
      enabled: true
      mode: placeholder

homepage:
  sections: []

booking_funnel:
  requirements: []
  constraints: []

technical:
  requirements: []
  exclusions: []

conversion:
  primary_goal: ""
  guidance: []

traceability:
  mandatory_for:
    - acceptance_criteria
    - slice_plans
    - pr_definition_of_done
  required_tags:
    - BRAND
    - TRUST
    - SAFETY
    - PRICING
    - BOOKING
