meta:
  id: hybrid-orchestration-phase-a-model
  version: 1.0.0
  status: approved-for-implementation-planning
  owner: solution-architect
  date: 2026-02-26
  issue: 6
  branch: feat/hybrid-memory-hierarchy-parallel-graph

scope:
  phase: A
  title: Foundations
  in_scope:
    - Hybrid orchestrator contract and fallback behavior
    - Memory hierarchy L1/L2/L3 context composition
    - Dependency graph DAG validation and deterministic wave planning
    - Feature flag controls for independent subsystem disable
  out_of_scope:
    - Parallel dispatch runtime execution
    - Checkpoint/replay and circuit breaker runtime
    - Telemetry dashboard rollout analytics

domain_entities:
  - name: HybridExecutionConfig
    fields:
      mode: sequential|hybrid
      flags: HybridFeatureFlags
      max_context_tokens: integer
      l1_token_budget: integer
      max_l2_comments: integer

  - name: HybridFeatureFlags
    fields:
      hybrid_orchestration_enabled: boolean
      parallel_graph_enabled: boolean
      memory_hierarchy_enabled: boolean

  - name: ContextSlice
    fields:
      tier: L1|L2|L3
      source: string
      content: string
      estimated_tokens: integer

  - name: ContextHierarchyResult
    fields:
      slices: ContextSlice[]
      total_estimated_tokens: integer
      truncated: boolean

  - name: DependencyGraphNode
    fields:
      id: string
      title: string
      agent: AgentId
      depends_on: string[]
      priority: P0|P1|P2|P3

  - name: DependencyGraphValidation
    fields:
      valid: boolean
      cycle_path: string[]?

relationships:
  - from: HybridExecutionConfig
    to: HybridFeatureFlags
    cardinality: 1:1
  - from: ContextHierarchyResult
    to: ContextSlice
    cardinality: 1:N
  - from: DependencyGraphValidation
    to: DependencyGraphNode
    cardinality: 1:N (validation target set)

state_machine:
  name: HybridOrchestrationMode
  states:
    - sequential
    - hybrid
  transitions:
    - from: sequential
      to: hybrid
      guard:
        - flags.hybrid_orchestration_enabled == true
        - config.mode == hybrid
    - from: hybrid
      to: sequential
      guard:
        - flags.hybrid_orchestration_enabled == false OR config.mode == sequential
      action: fallback_reason_set
  forbidden_transitions:
    - from: sequential
      to: parallel_graph_execution
      reason: Parallel graph cannot execute unless mode=hybrid and parallel_graph_enabled=true

invariants:
  - id: INV-HYB-001
    rule: Sequential fallback is always available and selected when hybrid is disabled.
  - id: INV-HYB-002
    rule: Dependency graph validation must reject cyclic inputs and return a cycle path.
  - id: INV-HYB-003
    rule: Context composition output must include per-slice token estimates.
  - id: INV-HYB-004
    rule: L1/L2/L3 content must be sanitized to redact secrets and PII patterns.
  - id: INV-HYB-005
    rule: Feature flags must independently control memory hierarchy and parallel graph behavior.
  - id: INV-HYB-006
    rule: Deterministic wave planning requires stable lexicographic node ordering.

trust_boundaries:
  zones:
    - name: agent-runtime
      trust_level: high
      contains:
        - hybrid-orchestrator.ts
        - dependency-graph.ts
        - context-hierarchy.ts
    - name: external-context-sources
      trust_level: medium
      contains:
        - github issue/pr comments (L2)
        - canonical docs source files (L3)
  boundary_rules:
    - All external-context-sources content must be sanitized before entering prompt slices.
    - No secrets, tokens, passwords, raw email addresses, or card-like data are allowed in emitted slices.

amm_os_extensions:
  tenant_model:
    current_mode: single-tenant
    tenant_key_ready: tenant_id (reserved for future extension)
  config_hierarchy:
    precedence:
      - runtime override
      - repository config
      - safe defaults
  feature_flags:
    provider: repository/runtime config (Phase A)
    flags:
      - hybrid_orchestration_enabled
      - parallel_graph_enabled
      - memory_hierarchy_enabled
