meta:
  id: issue29-continuous-improvement-architecture-brief
  version: 1.0.0
  status: proposed-for-implementation-planning
  owner: solution-architect
  date: 2026-02-27
  issue: 29
  source_handoff: .github/.handoffs/solution-architect/handoff-20260227-issue29-continuous-improvement-program.md
  canonical_profile: .github/.system-state/model/business_owner_profile.zaine.yaml

classification:
  type: continuous-improvement-program
  priority: P0-P1
  risk_tier: T2
  traceability_tags: [BRAND, TRUST, SAFETY, PRICING, BOOKING]

selected_tranche:
  slices:
    - id: I29-S1
      name: trust-critical-funnel-reliability-baseline
      maps_to_story: 29.1
      priority: P0
    - id: I29-S2
      name: booking-and-pricing-clarity-content-first
      maps_to_story: 29.2
      priority: P0
    - id: I29-S3
      name: accessibility-aa-core-pages
      maps_to_story: 29.3
      priority: P1
    - id: I29-S4
      name: seo-technical-baseline-hardening
      maps_to_story: 29.4
      priority: P1
    - id: I29-S5
      name: security-privacy-log-redaction-enforcement
      maps_to_story: 29.5
      priority: P1

model_deltas_required_before_implementation:
  - delta_id: D29-MODEL-001
    area: system_state
    requirement: Add continuous-improvement KPI entities and acceptance trace objects scoped to stories 29.1-29.5.
    deliverables:
      - KPI thresholds with probe definitions and evidence source
      - acceptance criteria IDs mapped to traceability tags
      - deterministic fail/pass semantics for each KPI
    tags: [TRUST, BOOKING, SAFETY]

  - delta_id: D29-MODEL-002
    area: contracts
    requirement: Extend API error-schema contract with mandatory redaction-safe error envelope for public APIs.
    deliverables:
      - required fields: errorCode, message, retryable, correlationId
      - forbidden fields: raw email, phone, free-text body, stack traces
      - deterministic validation status mapping per endpoint
    tags: [SAFETY, TRUST]

  - delta_id: D29-MODEL-003
    area: security
    requirement: Define and enforce sensitive-field redaction matrix across auth/contact/review/booking endpoints.
    deliverables:
      - sensitive_fields inventory
      - redaction policy and test probes
      - CI blocking behavior for redaction failures
    tags: [SAFETY, TRUST]

  - delta_id: D29-MODEL-004
    area: resilience
    requirement: Define trust-critical flow SLOs and rollback triggers aligned to DNS fallback posture.
    deliverables:
      - p95 latency and success-rate thresholds
      - trigger thresholds for rollback readiness
      - rollback checkpoint criteria per release phase
    tags: [TRUST, BOOKING]

  - delta_id: D29-MODEL-005
    area: observability
    requirement: Define KPI instrumentation points and alerting contracts before KPI claims are accepted.
    deliverables:
      - event and metric names for booking start, contact success, API failures
      - dashboard ownership and evidence cadence
      - MTTD objective: <15 minutes
    tags: [TRUST, BOOKING, BRAND]

core_invariants:
  - id: INV-I29-001
    rule: Trust-critical public API responses always conform to contract-valid success or redaction-safe error envelope.
    tags: [TRUST, SAFETY, BOOKING]
  - id: INV-I29-002
    rule: Booking CTA is present and actionable above the fold on all required public pages.
    tags: [BOOKING, BRAND]
  - id: INV-I29-003
    rule: Pricing copy remains decision-safe until business-owner selected_option_id is finalized.
    tags: [PRICING, TRUST]
  - id: INV-I29-004
    rule: WCAG 2.2 AA critical violations remain zero on Home, Pricing, Book, Contact before release progression.
    tags: [TRUST, SAFETY, BOOKING]
  - id: INV-I29-005
    rule: robots.txt and sitemap.xml remain available with valid content and canonical public route coverage.
    tags: [BOOKING, TRUST]
  - id: INV-I29-006
    rule: No payment card data enters app-owned logs, state, or persistence; PCI remains delegated to Square.
    tags: [SAFETY, TRUST, BOOKING]

state_machines:
  - name: ContinuousImprovementSliceLifecycle
    states:
      - proposed
      - modeled
      - implementation_ready
      - in_delivery
      - evidence_pending
      - gate_passed
      - gate_failed
      - rolled_back
    transitions:
      - from: proposed
        to: modeled
        guard: model_deltas_approved
      - from: modeled
        to: implementation_ready
        guard: contracts_security_and_delivery_models_present
      - from: implementation_ready
        to: in_delivery
        guard: feature_branch_open_and_owners_assigned
      - from: in_delivery
        to: evidence_pending
        guard: code_complete_and_quality_checks_green
      - from: evidence_pending
        to: gate_passed
        guard: required_evidence_attached_and_validated
      - from: evidence_pending
        to: gate_failed
        guard: missing_or_failed_evidence
      - from: gate_failed
        to: rolled_back
        guard: rollback_trigger_threshold_crossed
      - from: gate_failed
        to: in_delivery
        guard: remediation_plan_approved
    forbidden_transitions:
      - from: proposed
        to: in_delivery
        reason: model-first governance prohibits implementation without model completion
      - from: in_delivery
        to: gate_passed
        reason: evidence phase cannot be skipped

kpi_thresholds:
  ux_design:
    U1_hero_comprehension_score_min: 85
    U2_booking_cta_visibility_key_pages_percent: 100
    U3_bounce_rate_reduction_home_pricing_percent_min: 15
  accessibility:
    A1_wcag22aa_critical_violations_core_pages: 0
    A2_keyboard_only_booking_initiation_success_percent_min: 95
    A3_interactive_element_contrast_failures: 0
  performance:
    P1_lcp_mobile_p75_ms_max: 1200
    P2_inp_mobile_p75_ms_max: 200
    P3_cls_p75_max: 0.05
    P4_booking_api_p95_latency_ms_max: 2000
  seo:
    S1_robots_and_sitemap_status: 200
    S2_unique_metadata_coverage_required_pages_percent: 100
    S3_indexed_valid_pages_coverage_percent_min: 95
  conversion:
    C1_booking_start_rate_improvement_percent_min: 20
    C2_contact_form_server_acceptance_percent_min: 98
    C3_pricing_comprehension_score_percent_min: 90
  reliability:
    R1_uptime_percent_min: 99.9
    R2_critical_flow_success_percent_min: 99
    R3_dns_fallback_drill_minutes_max: 5
  security:
    Sec1_card_data_touchpoints_in_app: 0
    Sec2_high_severity_dependency_findings_open: 0
    Sec3_sensitive_field_redaction_pass_rate_percent: 100
  release_quality:
    D1_pr_quality_gate_pass_rate_percent_min: 95
    D2_mttd_production_critical_minutes_max: 15
    D3_model_traceability_on_merged_changes_percent: 100

dependency_gates:
  - gate_id: G29-PRICING-DECISION
    rule: Final numeric pricing copy blocked until canonical profile selected_option_id != TBD.
    owner: business-owner
    tags: [PRICING, TRUST]
  - gate_id: G29-MODEL-COMPLETE
    rule: contracts/security/resilience/observability deltas must be present before implementation dispatch.
    owner: solution-architect
    tags: [TRUST, SAFETY, BOOKING]
  - gate_id: G29-ROLLBACK-SAFETY
    rule: No slice may degrade DNS fallback posture or exceed rollback window of 5 minutes.
    owner: tech-lead
    tags: [TRUST, BOOKING]
