meta:
  id: issue26-p0-trust-booking-brand-architecture-brief
  version: 1.0.0
  status: proposed-for-implementation-planning
  owner: solution-architect
  date: 2026-02-27
  issue: 26
  source_handoffs:
    - .github/.handoffs/00-chief-of-staff/handoff-20260227-134500.md
    - .github/.handoffs/solution-architect/handoff-20260227-140900.md
  canonical_profile: .github/.system-state/model/business_owner_profile.zaine.yaml

classification:
  type: bug-and-feature-correction
  priority: P0
  risk_tier: T2
  traceability_tags: [BRAND, TRUST, SAFETY, PRICING, BOOKING]

problem_statement:
  - Booking flow blocks at availability and does not reliably transition to suite selection.
  - Magic-link sign-in presents configuration failure to end users.
  - Contact and review submit flows lack verified persistence and confirmation semantics.
  - SEO baseline endpoints are missing (robots/sitemap), reducing trust and discoverability.
  - Public positioning drifts from canonical small-capacity private boarding profile.

scope:
  p0_in_scope:
    - booking availability progression and recoverable failure states
    - auth magic-link request validation and failure-safe UX path
    - contact submit persistence, idempotency, anti-abuse and confirmation
    - review moderation submit persistence with publish gating
    - seo baseline contracts for robots.txt and sitemap.xml
    - metadata naming consistency with canonical brand
  out_of_scope:
    - new service lines and IA expansion
    - speculative visual redesign or experimental UX
    - payment architecture changes beyond current delegated PCI boundaries

domain_entities:
  - name: BookingRequest
    fields:
      check_in: date
      check_out: date
      service_type: boarding
      party_size: integer
      suite_preference: string?
      customer_email: string
      idempotency_key: string
  - name: AvailabilityResult
    fields:
      is_available: boolean
      reason_code: NONE|NO_CAPACITY|BLACKOUT|INVALID_RANGE|SERVICE_UNAVAILABLE
      next_retry_after_seconds: integer?
      response_time_ms: integer
  - name: MagicLinkRequest
    fields:
      email: string
      intent: sign_in|manage_booking
      correlation_id: string
  - name: ContactSubmission
    fields:
      full_name: string
      email: string
      phone: string?
      message: string
      idempotency_key: string
      anti_abuse_token: string
  - name: ReviewSubmission
    fields:
      display_name: string
      rating: integer
      title: string
      body: string
      stay_month: string?
      moderation_status: pending|approved|rejected
      idempotency_key: string
  - name: SeoAssetContract
    fields:
      robots_txt_status: 200
      sitemap_xml_status: 200
      canonical_brand_string: "Zaine's Stay & Play"

state_machines:
  - name: BookingAvailabilityFlow
    states:
      - idle
      - validating_input
      - checking_availability
      - available
      - unavailable_recoverable
      - invalid_input
      - service_degraded
    transitions:
      - from: idle
        to: validating_input
        guard:
          - user_action == continue
      - from: validating_input
        to: invalid_input
        guard:
          - check_out <= check_in
      - from: validating_input
        to: checking_availability
        guard:
          - check_out > check_in
      - from: checking_availability
        to: available
        guard:
          - result.is_available == true
          - response_time_ms <= 2000 (p95 target)
      - from: checking_availability
        to: unavailable_recoverable
        guard:
          - result.reason_code in [NO_CAPACITY, BLACKOUT]
      - from: checking_availability
        to: service_degraded
        guard:
          - result.reason_code == SERVICE_UNAVAILABLE
    forbidden_transitions:
      - from: invalid_input
        to: available
        reason: must correct date range before retry

  - name: MagicLinkFlow
    states: [idle, validating_email, sending_link, sent, invalid_email, provider_misconfigured, transient_failure]
    transitions:
      - from: idle
        to: validating_email
      - from: validating_email
        to: invalid_email
        guard: email_format_invalid
      - from: validating_email
        to: sending_link
        guard: email_format_valid
      - from: sending_link
        to: sent
        guard: provider_response in [200, 202]
      - from: sending_link
        to: provider_misconfigured
        guard: provider_error_class == configuration
      - from: sending_link
        to: transient_failure
        guard: provider_error_class == transient

  - name: ContactSubmissionFlow
    states: [draft, validating, submitting, submitted, submit_failed_retryable, throttled]
    transitions:
      - from: draft
        to: validating
      - from: validating
        to: submitting
        guard: schema_valid
      - from: validating
        to: draft
        guard: schema_invalid
      - from: submitting
        to: submitted
        guard: persistence_success
      - from: submitting
        to: throttled
        guard: rate_limit_exceeded
      - from: submitting
        to: submit_failed_retryable
        guard: persistence_failure

  - name: ReviewModerationFlow
    states: [draft, validating, submitting, moderation_pending, rejected_validation]
    transitions:
      - from: draft
        to: validating
      - from: validating
        to: rejected_validation
        guard: schema_invalid
      - from: validating
        to: submitting
        guard: schema_valid
      - from: submitting
        to: moderation_pending
        guard: persistence_success
    publish_rule:
      - public_listing_requires: moderation_status == approved

invariants:
  - id: INV-I26-001
    rule: Booking progression to suite selection is enabled only from BookingAvailabilityFlow.available.
    tags: [BOOKING, TRUST]
  - id: INV-I26-002
    rule: Invalid date ranges never trigger availability network requests.
    tags: [BOOKING, SAFETY]
  - id: INV-I26-003
    rule: Magic-link provider configuration failures return support-safe UI copy and actionable server log code.
    tags: [TRUST, BOOKING]
  - id: INV-I26-004
    rule: Contact and review submits require backend persistence acknowledgment before success UI is shown.
    tags: [TRUST, BOOKING]
  - id: INV-I26-005
    rule: Pending or rejected reviews are never publicly listed.
    tags: [TRUST, BRAND]
  - id: INV-I26-006
    rule: Public SEO assets robots.txt and sitemap.xml return HTTP 200 in production.
    tags: [BRAND, TRUST, BOOKING]
  - id: INV-I26-007
    rule: Public-facing metadata/title strings use canonical brand naming and avoid legacy mixed strings.
    tags: [BRAND, TRUST]

security_and_privacy:
  trust_boundaries:
    - zone: browser-client
      level: untrusted
    - zone: nextjs-server-actions-and-api
      level: trusted
    - zone: auth-provider
      level: external-trusted-via-contract
  required_controls:
    - validate all form inputs server-side with strict schema
    - log correlation codes, not raw PII; redact email/phone in error logs
    - keep PCI delegation intact; no card data in this scope
    - anti-abuse limits on contact and review submit endpoints

seo_and_metadata_requirements:
  robots:
    path: /robots.txt
    status: 200
    minimum_directives:
      - User-agent: '*'
      - Allow: '/'
      - Sitemap: https://zaines.vercel.app/sitemap.xml
  sitemap:
    path: /sitemap.xml
    status: 200
    required_urls:
      - /
      - /about
      - /pricing
      - /book
      - /contact
  metadata:
    canonical_brand: "Zaine's Stay & Play"
    keyword_baseline:
      - syracuse dog boarding
      - private dog boarding syracuse
      - small dog boarding syracuse

release_sequencing:
  - slice: S1-booking-availability-reliability
    priority: P0
    dependencies: []
  - slice: S2-auth-magic-link-reliability
    priority: P0
    dependencies: [S1-booking-availability-reliability]
  - slice: S3-contact-review-persistence
    priority: P0
    dependencies: [S1-booking-availability-reliability]
  - slice: S4-seo-metadata-baseline
    priority: P1
    dependencies: [S1-booking-availability-reliability, S2-auth-magic-link-reliability, S3-contact-review-persistence]
  - slice: S5-brand-pricing-copy-alignment
    priority: P1
    dependencies: [S4-seo-metadata-baseline]
