meta:
  id: issue31-p0-pricing-integrity-trust-consistency-architecture-brief
  version: 1.0.0
  status: ready-for-tech-lead-planning
  owner: solution-architect
  date: 2026-02-27
  issue: 31
  source_handoffs:
    - .github/.handoffs/00-chief-of-staff/handoff-20260227-pricing-trust-demand.md
    - .github/.handoffs/solution-architect/handoff-20260227-issue31-pricing-integrity-trust-consistency.md
  canonical_profile: .github/.system-state/model/business_owner_profile.zaine.yaml

classification:
  type: trust-critical-pricing-consistency-correction
  priority: P0
  risk_tier: T2
  traceability_tags: [PRICING, TRUST, BOOKING, BRAND]

problem_statement:
  - Public funnel routes contain contradictory pricing and add-on language that conflicts with transparency promises.
  - Booking pre-confirmation semantics do not guarantee explicit subtotal, tax, and total clarity in one canonical language model.
  - Pricing policy messaging can drift across routes without deterministic content guards.

scope:
  p0_in_scope:
    - content policy normalization across Home, Pricing, Book, Contact, Reviews, FAQ, Policies
    - no-surprise-add-ons enforcement in pricing and booking experiences
    - booking price-before-confirmation clarity with explicit pricing model and tax language
    - business-profile copy conformance to premium-fair transparency-first voice
    - regression protection for pricing copy and booking quote/API consistency
  out_of_scope:
    - pricing calculator redesign
    - promotions, discounts, or net-new service-line pricing models
    - payment provider architecture changes

domain_entities:
  - name: PricingPolicyProfile
    fields:
      transparency_claims_required: string[]
      forbidden_pricing_claims: string[]
      route_scope: route[]
      pricing_model_mode: enum[decision_safe, base_plus_tax, tax_inclusive_flat]
  - name: RoutePricingMessage
    fields:
      route: route
      allows_add_on_language: boolean
      required_claim_keys: string[]
      forbidden_claim_keys: string[]
      last_verified_at: datetime
  - name: BookingQuoteDisclosure
    fields:
      subtotal: number
      tax: number
      total: number
      currency: string
      pricing_model_label: string
      shown_before_confirmation: boolean

state_machines:
  - name: RoutePricingConsistencyFlow
    states:
      - draft
      - normalized
      - verified
      - rejected_for_drift
    transitions:
      - from: draft
        to: normalized
        guard:
          - route_copy_contains_all_required_claims
          - route_copy_contains_no_forbidden_claims
      - from: normalized
        to: verified
        guard:
          - route_test_assertions_pass
      - from: normalized
        to: rejected_for_drift
        guard:
          - contradictory_claim_detected
      - from: rejected_for_drift
        to: draft
        guard:
          - copy_updated_for_policy_alignment

  - name: BookingPreConfirmationPricingFlow
    states:
      - quote_computing
      - quote_ready
      - quote_invalid
      - ready_for_confirmation
    transitions:
      - from: quote_computing
        to: quote_ready
        guard:
          - subtotal_tax_total_present
          - pricing_model_label_present
      - from: quote_computing
        to: quote_invalid
        guard:
          - any_required_price_field_missing
      - from: quote_ready
        to: ready_for_confirmation
        guard:
          - user_has_seen_pricing_disclosure == true
    forbidden_transitions:
      - from: quote_computing
        to: ready_for_confirmation
        reason: pre-confirmation pricing disclosure must be complete first
      - from: quote_invalid
        to: ready_for_confirmation
        reason: invalid quote cannot proceed to confirmation

invariants:
  - id: INV-I31-001
    rule: Required routes (/, /pricing, /book, /contact, /reviews, /faq, /policies) always publish pricing policy claims with no contradictions.
    tags: [PRICING, TRUST, BRAND]
  - id: INV-I31-002
    rule: Public pricing language never uses surprise add-on framing on in-scope routes.
    tags: [PRICING, TRUST]
  - id: INV-I31-003
    rule: Booking confirmation is blocked unless subtotal, tax, total, and pricing model label are disclosed before confirmation.
    tags: [PRICING, BOOKING, TRUST]
  - id: INV-I31-004
    rule: Pricing copy remains decision-safe when business_profile.service.boarding.rate.selected_option_id is TBD.
    tags: [PRICING, TRUST]
  - id: INV-I31-005
    rule: Pricing copy preserves premium-but-fair positioning and avoids discount/budget framing.
    tags: [BRAND, PRICING, TRUST]

route_policy_matrix:
  required_routes:
    - /
    - /pricing
    - /book
    - /contact
    - /reviews
    - /faq
    - /policies
  required_claim_keys:
    - clear_pricing_before_confirmation
    - no_hidden_fees
    - no_surprise_add_ons
    - premium_but_fair
  forbidden_claim_keys:
    - generic_add_on_upsell_framing
    - contradictory_tax_messages
    - hidden_fee_language
    - discount_or_budget_positioning

release_slices:
  - slice_id: I31-S1
    title: cross-route pricing policy normalization
    priority: P0
    dependencies: []
    acceptance_criteria:
      - AC-I31-001
      - AC-I31-002
  - slice_id: I31-S2
    title: booking pre-confirmation disclosure semantics
    priority: P0
    dependencies:
      - I31-S1
    acceptance_criteria:
      - AC-I31-003
  - slice_id: I31-S3
    title: regression protection and evidence hardening
    priority: P0
    dependencies:
      - I31-S1
      - I31-S2
    acceptance_criteria:
      - AC-I31-004
      - AC-I31-005

next_biggest_thing_proposal:
  id: I31-NBT-P1
  title: Brand authenticity and trust narrative alignment
  effort: M
  rationale: Requires coordinated copy audit across About and supporting trust surfaces, but no net-new infrastructure.
  acceptance_criteria:
    - remove generic_or_fabricated_personas_from_about_page
    - align about_narrative_to_owner_led_syracuse_local_profile
    - require evidence_backed_trust_claims_only
  traceability_tags: [BRAND, TRUST, SAFETY]
