meta:
  id: issue26-p0-trust-booking-brand-risk-register
  version: 1.0.0
  status: active
  owner: solution-architect
  date: 2026-02-27
  issue: 26

risk_register:
  - risk_id: R-26-001
    title: Pricing option unresolved for public copy lock
    category: pricing
    severity: high
    likelihood: medium
    impact:
      - pricing page ambiguity
      - booking summary mismatch risk
      - trust erosion from inconsistent totals
    owner: business-owner
    trigger:
      - selected_option_id remains TBD in canonical profile
    mitigation:
      - hold public pricing copy to approved neutral wording until decision
      - block release of final pricing language unless decision captured in canonical profile model
    contingency:
      - if unresolved at release gate, ship non-ambiguous compliance-safe copy without unapproved numeric claims
    status: open
    traceability_tags: [PRICING, TRUST, BOOKING]

  - risk_id: R-26-002
    title: Stakeholder approval pending for brand repositioning scope
    category: brand
    severity: high
    likelihood: medium
    impact:
      - conflicting messaging between pages
      - delay in P1 copy alignment
      - reduced conversion confidence
    owner: chief-of-staff
    trigger:
      - unresolved review comments on de-emphasis of broad "pet resort" positioning
    mitigation:
      - enforce canonical profile as source of truth for all edited copy
      - require explicit approval checkpoint before full copy freeze
    contingency:
      - if pending, prioritize P0 functional fixes and isolate brand copy updates in gated slice
    status: open
    traceability_tags: [BRAND, TRUST, BOOKING]

  - risk_id: R-26-003
    title: Availability dependency instability causes booking funnel regression
    category: booking-reliability
    severity: critical
    likelihood: medium
    impact:
      - inability to complete bookings
      - direct conversion loss
    owner: tech-lead
    trigger:
      - availability endpoint p95 exceeds 2s or >=1% 5xx rate
    mitigation:
      - explicit retry semantics and recoverable degraded state UX
      - enforce guard that invalid dates do not dispatch requests
    contingency:
      - temporarily fail closed with actionable fallback messaging and assisted contact path
    status: open
    traceability_tags: [BOOKING, TRUST, SAFETY]

  - risk_id: R-26-004
    title: Sensitive logging in auth/contact flows
    category: security-compliance
    severity: high
    likelihood: low
    impact:
      - trust/compliance risk from raw PII in logs
    owner: security-engineer
    trigger:
      - logs include full email, phone, or message content at error level
    mitigation:
      - redact sensitive fields and log only correlation IDs + error codes
      - add pre-merge log review checklist item for impacted routes
    contingency:
      - block deployment if redaction checks fail
    status: open
    traceability_tags: [TRUST, SAFETY]
