meta:
  id: issue26-p0-trust-booking-brand-implementation-plan
  version: 1.0.0
  status: ready-for-engineering-dispatch
  owner: tech-lead
  date: 2026-02-27
  issue: 26
  feature_branch: feature/26-p0-trust-booking-brand
  model_inputs:
    - .github/.system-state/model/issue26_p0_trust_booking_brand_architecture_brief.yaml
    - .github/.system-state/contracts/issue26_p0_trust_booking_brand_contracts.yaml
    - .github/.system-state/model/issue26_p0_trust_booking_brand_risk_register.yaml
  traceability_tags: [BRAND, TRUST, SAFETY, PRICING, BOOKING]

planning_rules:
  model_first_sequence: true
  no_ui_polish_before_contract_state_alignment: true
  p0_must_complete_before_p1_merge: true
  p95_response_target_ms: 2000

implementation_tickets:
  - ticket_id: I26-S1
    slice: S1-booking-availability-reliability
    priority: P0
    owner_pair:
      frontend_engineer: frontend-engineer
      backend_engineer: backend-engineer
    dependencies: []
    contracts:
      - POST /api/booking/availability
    invariants:
      - INV-I26-001
      - INV-I26-002
    scope:
      backend:
        - Implement strict request schema validation and invalid date-range guard.
        - Return deterministic error codes: INVALID_DATE_RANGE, AVAILABILITY_UNAVAILABLE.
        - Emit correlationId on all non-2xx responses.
      frontend:
        - Implement state machine: idle -> validating_input -> checking_availability -> available|unavailable_recoverable|service_degraded|invalid_input.
        - Block network dispatch when checkOut <= checkIn.
        - Render retry-safe non-technical degraded copy.
    acceptance_criteria:
      - AC-P0-1-booking-progression
    tags: [BOOKING, TRUST, SAFETY]
    done_definition:
      - Invalid date range does not trigger availability request.
      - Continue path to suite selection enabled only in available state.
      - Failure states render non-technical user copy with retry affordance.

  - ticket_id: I26-S2
    slice: S2-auth-magic-link-reliability
    priority: P0
    owner_pair:
      frontend_engineer: frontend-engineer
      backend_engineer: backend-engineer
    dependencies: [I26-S1]
    contracts:
      - POST /api/auth/magic-link
    invariants:
      - INV-I26-003
    scope:
      backend:
        - Validate email and intent schema.
        - Map provider errors to INVALID_EMAIL, AUTH_PROVIDER_MISCONFIGURED, AUTH_TRANSIENT_FAILURE.
        - Log actionable error code + correlationId with redacted PII.
      frontend:
        - Add deterministic UX states: idle, validating_email, sending_link, sent, invalid_email, provider_misconfigured, transient_failure.
        - Surface support-safe user message for provider_misconfigured.
    acceptance_criteria:
      - AC-P0-2-auth-magic-link
    tags: [BOOKING, TRUST]
    done_definition:
      - Valid email returns sent confirmation path.
      - Provider internals are not exposed in client-visible copy.
      - Misconfigured and transient failures remain retry-safe and deterministic.

  - ticket_id: I26-S3
    slice: S3-contact-review-persistence
    priority: P0
    owner_pair:
      frontend_engineer: frontend-engineer
      backend_engineer: backend-engineer
    dependencies: [I26-S1]
    contracts:
      - POST /api/contact/submissions
      - POST /api/reviews/submissions
      - GET /api/reviews
    invariants:
      - INV-I26-004
      - INV-I26-005
    scope:
      backend:
        - Add idempotency key support for contact/review creates.
        - Enforce anti-abuse/rate limiting for contact submissions.
        - Persist submissions and return confirmation identifiers.
        - Enforce approved-only filter for GET /api/reviews.
      frontend:
        - Preserve entered values on retryable failures.
        - Show confirmation IDs on successful contact/review submission.
        - Keep review in moderation pending state after submit.
    acceptance_criteria:
      - AC-P0-3-contact-persistence
      - AC-P0-4-review-moderation
    tags: [TRUST, BRAND, BOOKING]
    done_definition:
      - Success UI is shown only after persistence acknowledgment.
      - Retry path preserves user-entered data.
      - Non-approved reviews are excluded from public listing.

  - ticket_id: I26-S4
    slice: S4-seo-metadata-baseline
    priority: P1
    owner_pair:
      frontend_engineer: frontend-engineer
      backend_engineer: backend-engineer
    dependencies: [I26-S1, I26-S2, I26-S3]
    contracts:
      - GET /robots.txt
      - GET /sitemap.xml
    invariants:
      - INV-I26-006
      - INV-I26-007
    scope:
      backend:
        - Implement metadata route handlers for robots and sitemap.
      frontend:
        - Apply canonical brand metadata string to required pages.
    acceptance_criteria:
      - AC-P1-3-seo-baseline
    tags: [BRAND, TRUST, BOOKING]

  - ticket_id: I26-S5
    slice: S5-brand-pricing-copy-alignment
    priority: P1
    owner_pair:
      frontend_engineer: frontend-engineer
      backend_engineer: backend-engineer
    dependencies: [I26-S4]
    contracts: []
    invariants:
      - INV-I26-007
    scope:
      frontend:
        - Align copy to canonical private three-suite positioning and trust pillars.
        - Keep pricing text neutral until option decision is finalized.
      backend:
        - Ensure booking summary text contract stays aligned with approved pricing option.
    blocked_by_decisions:
      - R-26-001 pricing option decision
      - R-26-002 stakeholder brand-positioning approval
    tags: [BRAND, PRICING, TRUST]

qa_traceability_matrix:
  - slice_ticket: I26-S1
    acceptance_criteria:
      - id: AC-P0-1-booking-progression
        tags: [BOOKING, TRUST, SAFETY]
        tests_required:
          - invalid-date guard blocks request dispatch
          - availability success transitions to suite-selection-ready
          - 503 unavailable maps to recoverable retry state
        evidence_required:
          - API contract test for POST /api/booking/availability
          - UI state assertion test for booking flow transitions
          - production-like p95 sample <=2000ms

  - slice_ticket: I26-S2
    acceptance_criteria:
      - id: AC-P0-2-auth-magic-link
        tags: [BOOKING, TRUST]
        tests_required:
          - invalid email returns INVALID_EMAIL and blocks provider dispatch
          - provider misconfiguration maps to support-safe message
          - successful request returns deterministic sent state
        evidence_required:
          - API contract test for POST /api/auth/magic-link
          - redaction validation evidence for auth logs
          - UI test for success/misconfigured/transient state mapping

  - slice_ticket: I26-S3
    acceptance_criteria:
      - id: AC-P0-3-contact-persistence
        tags: [TRUST, BOOKING]
        tests_required:
          - successful contact submit returns confirmation id
          - retryable persistence failure preserves form values
          - throttled response returns CONTACT_RATE_LIMITED
        evidence_required:
          - API contract tests for POST /api/contact/submissions
          - persistence verification record for confirmation id
          - idempotency key duplicate submit test
      - id: AC-P0-4-review-moderation
        tags: [TRUST, BRAND]
        tests_required:
          - review validation errors block persistence
          - successful review submit returns moderation pending
          - GET /api/reviews excludes non-approved entries
        evidence_required:
          - API contract tests for POST /api/reviews/submissions and GET /api/reviews
          - moderation filter integration test

  - slice_ticket: I26-S4
    acceptance_criteria:
      - id: AC-P1-3-seo-baseline
        tags: [BRAND, TRUST, BOOKING]
        tests_required:
          - GET /robots.txt returns 200
          - GET /sitemap.xml returns 200
          - required URLs are present and canonical brand metadata is applied
        evidence_required:
          - route verification logs for robots/sitemap
          - metadata check results for /, /about, /pricing, /book, /contact

release_gate_routing:
  security_engineer:
    required_for:
      - I26-S1
      - I26-S2
      - I26-S3
    review_focus:
      - PII redaction in booking/auth/contact/review error logs
      - correlationId-only failure diagnostics
      - no provider internals exposed in client surfaces
  qa_test_engineer:
    required_for:
      - I26-S1
      - I26-S2
      - I26-S3
      - I26-S4
    review_focus:
      - AC gate evidence capture per qa_traceability_matrix
      - production-like validation for p95 <= 2000ms target
      - tag-complete traceability evidence: BRAND, TRUST, SAFETY, PRICING, BOOKING
