meta:
  id: hybrid-phase-a-threat-model
  version: 1.0.0
  owner: solution-architect
  date: 2026-02-26
  issue: 6

scope:
  components:
    - .github/framework/context-hierarchy.ts
    - .github/framework/dependency-graph.ts
    - .github/framework/hybrid-orchestrator.ts

attack_surfaces:
  - id: AS-CTX-001
    surface: L2/L3 untrusted text ingestion
    risk: secret_or_pii_leakage_into_prompts
    severity: high
    mitigation:
      - regex-based sanitization for api_key/secret/token/password/email patterns
      - budget capping to reduce oversized leakage blast radius

  - id: AS-GRAPH-001
    surface: user-supplied dependency graph
    risk: cycle_or_invalid_reference_causes_non-determinism
    severity: high
    mitigation:
      - dependency existence validation
      - cycle path detection and explicit failure
      - deterministic lexicographic sort before wave build

  - id: AS-FLAG-001
    surface: runtime feature flag misconfiguration
    risk: forced hybrid execution without fallback
    severity: medium
    mitigation:
      - sequential mode remains default-safe
      - hybrid requires both mode=hybrid and global flag enabled

security_invariants:
  - id: SEC-HYB-001
    rule: no direct card/payment data handling in Phase A modules
  - id: SEC-HYB-002
    rule: sanitize before token estimation and before emission in context slices
  - id: SEC-HYB-003
    rule: graph validation must fail closed (no waves when invalid)

compliance_notes:
  pci_scope: delegated_to_square_unchanged
  pii_policy: redact known identifiers from L2/L3 before downstream use
  logging_policy: do_not_log_raw_sensitive_context
