meta:
  id: issue29-continuous-improvement-threat-model
  version: 1.0.0
  owner: solution-architect
  date: 2026-02-27
  issue: 29
  scope_dependency: .github/.system-state/model/issue29_continuous_improvement_architecture_brief.yaml
  traceability_tags: [BRAND, TRUST, SAFETY, PRICING, BOOKING]

scope:
  slices:
    - I29-S1
    - I29-S2
    - I29-S3
    - I29-S4
    - I29-S5
  critical_routes:
    - /api/booking/availability
    - /api/auth/magic-link
    - /api/contact/submissions
    - /api/reviews/submissions
    - /robots.txt
    - /sitemap.xml

trust_boundaries:
  - zone: browser-client
    level: untrusted
  - zone: nextjs-api-and-server-components
    level: trusted
  - zone: persistence-and-queue
    level: trusted-internal
  - zone: square-platform
    level: external-trusted-via-contract
  - zone: analytics-observability-sinks
    level: restricted

attack_surfaces:
  - id: AS-I29-001
    surface: public API request payloads
    risk: schema bypass, malformed input, deterministic contract drift
    severity: high
    mitigations:
      - strict server-side schema validation on all public APIs
      - deterministic error envelope with correlationId
      - forbid stack trace leakage in responses
    slices: [I29-S1, I29-S5]

  - id: AS-I29-002
    surface: structured logging pipeline
    risk: raw PII exposure (email, phone, message free-text, auth headers)
    severity: critical
    mitigations:
      - field-level redaction policy before log emission
      - redaction probe tests required in CI and release gates
      - security owner approval required for any logging schema expansion
    slices: [I29-S1, I29-S5]

  - id: AS-I29-003
    surface: content/presentation updates for booking and pricing pages
    risk: misleading pricing claims and trust erosion from non-canonical copy
    severity: high
    mitigations:
      - canonical profile assertions in content QA checklist
      - pricing decision gate blocks unapproved numeric claims
      - prohibited-claims linting in review checklist
    slices: [I29-S2]

  - id: AS-I29-004
    surface: accessibility regressions in navigation/forms
    risk: inaccessible booking path for keyboard/screen-reader users
    severity: high
    mitigations:
      - WCAG 2.2 AA critical violations must be zero on core pages
      - keyboard path scripts with >=95% success threshold
      - form semantic contract checks for labels and error announcements
    slices: [I29-S3]

  - id: AS-I29-005
    surface: SEO route and metadata configuration
    risk: accidental indexing of non-public routes, missing crawl assets
    severity: medium
    mitigations:
      - robots/sitemap existence probes in release checks
      - metadata uniqueness + indexing policy validation
      - explicit exclusion rules for system/non-public routes
    slices: [I29-S4]

  - id: AS-I29-006
    surface: payment and booking boundaries
    risk: accidental app-level handling of card data breaking PCI delegation
    severity: critical
    mitigations:
      - Square-only payment boundary invariant
      - forbid card fields in app models, logs, and state
      - regression checks in security review evidence
    slices: [I29-S1, I29-S5]

security_invariants:
  - id: SEC-I29-001
    rule: All public API errors return correlationId and never return stack traces.
    tags: [TRUST, SAFETY]
  - id: SEC-I29-002
    rule: Sensitive fields are redacted 100% before logs are persisted or exported.
    tags: [SAFETY, TRUST]
  - id: SEC-I29-003
    rule: Pricing copy cannot publish non-approved numeric claims while selected_option_id is TBD.
    tags: [PRICING, TRUST]
  - id: SEC-I29-004
    rule: Non-public/system routes remain excluded from indexing policy.
    tags: [SAFETY, TRUST]
  - id: SEC-I29-005
    rule: Card data is never processed or stored in app-managed systems.
    tags: [SAFETY, TRUST, BOOKING]

required_security_evidence:
  - redaction_probe_logs_for_public_api_failures
  - dependency_scan_artifact_high_severity_zero_open
  - pci_delegation_data_flow_checklist
  - api_error_envelope_samples_showing_correlationId_without_stack
